// Curated question bank. Every top-level category has at least 30 questions so
// a single-category game can run multiple sessions before history is exhausted.
const bank = [];
const slug = (s) => s.toLowerCase().normalize("NFKD").replace(/[\u0300-\u036f]/g, "").replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
function add(category, rows) {
  const existing = bank.filter((q) => q.category === category).length;
  rows.forEach(([prompt, answer, theme = null, aliases = []], index) => bank.push({
    id: `${slug(category)}-${String(existing + index + 1).padStart(3, "0")}`,
    category, theme, prompt, answer,
    acceptedAnswers: [answer, ...aliases].map((text) => ({ text, display: text !== answer })),
    match: { mode: /^\d{4}$/.test(answer) ? "year" : "text", fuzzy: !/^\d{4}$/.test(answer), optionalArticles: true },
    explanation: `${answer} is the accepted answer.`,
  }));
}

add("Movies", [
  ["What is the name of Han Solo's ship?", "Millennium Falcon", "Star Wars", ["the Millennium Falcon"]],
  ["Who is Luke Skywalker's twin sister?", "Leia Organa", "Star Wars", ["Princess Leia", "Leia"]],
  ["What species is Chewbacca?", "Wookiee", "Star Wars", ["Wookie"]],
  ["What is Baby Yoda's actual name?", "Grogu", "Star Wars"],
  ["Which Sith Lord was once Anakin Skywalker?", "Darth Vader", "Star Wars", ["Vader"]],
  ["What metal is bonded to Wolverine's skeleton?", "Adamantium", "Marvel Cinematic Universe"],
  ["What is Thor's hammer called?", "Mjolnir", "Marvel Cinematic Universe", ["Mjölnir"]],
  ["What nation is Black Panther king of?", "Wakanda", "Marvel Cinematic Universe"],
  ["What is Captain America's shield primarily made from?", "Vibranium", "Marvel Cinematic Universe"],
  ["What is Tony Stark's superhero name?", "Iron Man", "Marvel Cinematic Universe"],
  ["What kind of fish is Nemo?", "Clownfish", "Disney & Pixar", ["clown fish"]],
  ["Who is the space ranger in Toy Story?", "Buzz Lightyear", "Disney & Pixar", ["Buzz"]],
  ["What is the name of the rat chef in Ratatouille?", "Remy", "Disney & Pixar"],
  ["Which princess has a tiger named Rajah?", "Jasmine", "Disney & Pixar", ["Princess Jasmine"]],
  ["What is the snowman's name in Frozen?", "Olaf", "Disney & Pixar"],
  ["Who carries the One Ring to Mordor?", "Frodo Baggins", "The Lord of the Rings", ["Frodo"]],
  ["What creature does Gollum call his precious?", "The One Ring", "The Lord of the Rings", ["One Ring", "ring"]],
  ["Who is the wizard leader of the Fellowship?", "Gandalf", "The Lord of the Rings"],
  ["What dinosaur is the main threat in the first Jurassic Park?", "Tyrannosaurus rex", "Jurassic Park", ["T. rex", "T-Rex"]],
  ["Who directed Spirited Away?", "Hayao Miyazaki", "Studio Ghibli", ["Miyazaki"]],
]);

// Every named Movie theme has at least six entries, enough for the shortest
// focused game. General mixed games still balance at the top-level category.
add("Movies", [
  ["Who built the protocol droid C-3PO?", "Anakin Skywalker", "Star Wars", ["Anakin"]],
  ["Which Infinity Stone was set in Vision's forehead?", "Mind Stone", "Marvel Cinematic Universe", ["the Mind Stone"]],
  ["Who is Simba's father in The Lion King?", "Mufasa", "Disney & Pixar"],
  ["What is the reforged name of Aragorn's sword?", "Andúril", "The Lord of the Rings", ["Anduril"]],
  ["Which elf serves as the Fellowship's archer?", "Legolas", "The Lord of the Rings"],
  ["Which land is ruled by the horse-lords?", "Rohan", "The Lord of the Rings"],
  ["On what fictional island is the original Jurassic Park built?", "Isla Nublar", "Jurassic Park", ["Nublar"]],
  ["Who founded Jurassic Park in the first film?", "John Hammond", "Jurassic Park", ["Hammond"]],
  ["Which paleontologist is played by Sam Neill?", "Alan Grant", "Jurassic Park", ["Dr. Alan Grant", "Grant"]],
  ["What insect preserved in amber provides dinosaur DNA?", "Mosquito", "Jurassic Park", ["a mosquito"]],
  ["What genetics company created Jurassic Park's dinosaurs?", "InGen", "Jurassic Park", ["International Genetic Technologies"]],
  ["What forest spirit befriends Satsuki and Mei?", "Totoro", "Studio Ghibli", ["My Neighbor Totoro"]],
  ["What is the name of Kiki's black cat?", "Jiji", "Studio Ghibli"],
  ["Who owns the moving castle in Howl's Moving Castle?", "Howl", "Studio Ghibli", ["Howl Pendragon"]],
  ["Who is the young Emishi prince in Princess Mononoke?", "Ashitaka", "Studio Ghibli"],
  ["What kind of creature is Ponyo at the beginning of her film?", "Goldfish", "Studio Ghibli", ["fish"]],
]);

add("Movies", [
  ["On which planet does Yoda live in exile?", "Dagobah", "Star Wars"],
  ["What command triggered the clone army to turn on the Jedi?", "Order 66", "Star Wars", ["Execute Order 66"]],
  ["On which desert planet does Rey live when first introduced?", "Jakku", "Star Wars"],
  ["Which bounty hunter wears armor inherited from Jango Fett?", "Boba Fett", "Star Wars", ["Boba"]],
  ["What is the Hulk's human name?", "Bruce Banner", "Marvel Cinematic Universe", ["Dr. Bruce Banner", "Banner"]],
  ["What is Natasha Romanoff's superhero name?", "Black Widow", "Marvel Cinematic Universe"],
  ["Which Infinity Stone was housed in the Tesseract?", "Space Stone", "Marvel Cinematic Universe", ["the Space Stone"]],
  ["What superhero title is held by Wakanda's protector?", "Black Panther", "Marvel Cinematic Universe"],
  ["What is the family surname in Encanto?", "Madrigal", "Disney & Pixar", ["the Madrigals", "Madrigal family"]],
  ["What city do the monsters inhabit in Monsters, Inc.?", "Monstropolis", "Disney & Pixar"],
  ["What is the name of the Wilderness Explorer in Up?", "Russell", "Disney & Pixar"],
  ["What are Cinderella's two best-known mouse friends?", "Jaq and Gus", "Disney & Pixar", ["Jaq & Gus", "Gus and Jaq"]],
  ["What peaceful homeland do Frodo and Bilbo come from?", "The Shire", "The Lord of the Rings", ["Shire"]],
  ["Which kingdom does Boromir defend?", "Gondor", "The Lord of the Rings"],
  ["What was Gollum's name before he took the Ring?", "Sméagol", "The Lord of the Rings", ["Smeagol"]],
  ["Which Ent leads the march on Isengard?", "Treebeard", "The Lord of the Rings"],
  ["Which chaos theorist is played by Jeff Goldblum?", "Ian Malcolm", "Jurassic Park", ["Dr. Ian Malcolm", "Malcolm"]],
  ["What is the name of Owen Grady's trained velociraptor?", "Blue", "Jurassic Park"],
  ["Who trains velociraptors in Jurassic World?", "Owen Grady", "Jurassic Park", ["Owen"]],
  ["Which towering dinosaur is the first living dinosaur the visitors see in Jurassic Park?", "Brachiosaurus", "Jurassic Park"],
  ["What is the heroine's name in Spirited Away?", "Chihiro", "Studio Ghibli", ["Chihiro Ogino", "Sen"]],
  ["What fire demon powers Howl's moving castle?", "Calcifer", "Studio Ghibli"],
  ["Which princess explores the toxic jungle in Nausicaä of the Valley of the Wind?", "Nausicaä", "Studio Ghibli", ["Nausicaa"]],
  ["What is the floating castle called in Castle in the Sky?", "Laputa", "Studio Ghibli"],
]);

add("Movies", [
  ["Who directed Titanic?", "James Cameron", null, ["Cameron"]],
  ["What name does Thomas Anderson use in The Matrix?", "Neo"],
  ["What is the crime-family surname in The Godfather?", "Corleone", null, ["the Corleone family"]],
  ["What planet is E.T. trying to return to?", "His home planet", null, ["home"]],
  ["What kind of animal terrorizes Amity Island in Jaws?", "Great white shark", null, ["shark"]],
  ["What car is used as the time machine in Back to the Future?", "DeLorean", null, ["DMC DeLorean"]],
  ["Who follows the Yellow Brick Road in The Wizard of Oz?", "Dorothy Gale", null, ["Dorothy"]],
  ["What is the first name of Russell Crowe's character in Gladiator?", "Maximus", null, ["Maximus Decimus Meridius"]],
  ["On what moon is Avatar primarily set?", "Pandora"],
  ["What object is Cobb's totem in Inception?", "Spinning top", null, ["top"]],
  ["In which Moroccan city is the film Casablanca set?", "Casablanca"],
  ["What prison gives The Shawshank Redemption its title?", "Shawshank State Penitentiary", null, ["Shawshank Prison", "Shawshank"]],
  ["In which city do the Ghostbusters operate?", "New York City", null, ["New York", "NYC"]],
  ["What is Indiana Jones's profession?", "Archaeologist", null, ["an archaeologist"]],
  ["Who is the central IMF agent in the Mission: Impossible films?", "Ethan Hunt", null, ["Hunt"]],
]);

add("Books", [
  ["What house is Harry Potter sorted into?", "Gryffindor", "Harry Potter"],
  ["What is Harry Potter's owl named?", "Hedwig", "Harry Potter"],
  ["Who is Hogwarts' headmaster at the start of the series?", "Albus Dumbledore", "Harry Potter", ["Dumbledore"]],
  ["What platform does the Hogwarts Express depart from?", "Platform 9¾", "Harry Potter", ["Platform 9 3/4", "9¾", "9 3/4"]],
  ["What sport is played on flying broomsticks?", "Quidditch", "Harry Potter"],
  ["What is Hermione's surname?", "Granger", "Harry Potter", ["Hermione Granger"]],
  ["What creature guards the Philosopher's Stone trapdoor?", "Fluffy", "Harry Potter", ["three-headed dog"]],
  ["What spell disarms an opponent?", "Expelliarmus", "Harry Potter"],
  ["Which house has a snake as its emblem?", "Slytherin", "Harry Potter"],
  ["What is Voldemort's birth name?", "Tom Riddle", "Harry Potter", ["Tom Marvolo Riddle"]],
  ["Who wrote Pride and Prejudice?", "Jane Austen"],
  ["Who wrote 1984?", "George Orwell"],
  ["What is Sherlock Holmes's street address?", "221B Baker Street", null, ["221B Baker St"]],
  ["Which novel begins with the character Scout Finch?", "To Kill a Mockingbird"],
  ["Who wrote The Little Prince?", "Antoine de Saint-Exupéry", null, ["Antoine de Saint Exupery", "Saint-Exupéry"]],
  ["What is the surname of the sisters in Little Women?", "March"],
  ["Who created the detective Hercule Poirot?", "Agatha Christie"],
  ["What is the first book of The Chronicles of Narnia by publication order?", "The Lion, the Witch and the Wardrobe", null, ["Lion Witch and Wardrobe"]],
  ["Who wrote The Hobbit?", "J. R. R. Tolkien", null, ["JRR Tolkien", "Tolkien"]],
  ["What whale is pursued in Moby-Dick?", "Moby Dick", null, ["the white whale"]],
]);

add("The '90s", [
  ["In what year did the World Wide Web become publicly available?", "1991"],
  ["In what year was the first SMS text message sent?", "1992"],
  ["In what year did Jurassic Park premiere?", "1993"],
  ["In what year did Friends first air?", "1994"],
  ["In what year was Windows 95 released?", "1995"],
  ["In what year did Pokémon debut in Japan?", "1996"],
  ["In what year did the first Harry Potter novel publish in the UK?", "1997"],
  ["In what year was Google founded?", "1998"],
  ["In what year did The Matrix premiere?", "1999"],
  ["Which virtual pet toy became a global craze in the late 1990s?", "Tamagotchi"],
  ["Which girl group released Wannabe?", "Spice Girls", null, ["the Spice Girls"]],
  ["Which handheld Nintendo console was a defining 1990s toy?", "Game Boy", null, ["Nintendo Game Boy"]],
  ["What dance craze accompanied Los del Río's hit song?", "Macarena", null, ["the Macarena"]],
  ["Which sitcom featured Will Smith moving to Bel-Air?", "The Fresh Prince of Bel-Air", null, ["Fresh Prince of Bel Air"]],
  ["What storage format commonly held 1.44 MB on personal computers?", "Floppy disk", null, ["3.5-inch floppy disk", "floppy"]],
  ["Which arcade fighting series introduced Scorpion and Sub-Zero?", "Mortal Kombat"],
  ["Which singer was known as the Princess of Pop after ...Baby One More Time?", "Britney Spears", null, ["Britney"]],
  ["What was the name of the cloned sheep announced in 1997?", "Dolly", null, ["Dolly the sheep"]],
  ["Which basketball star led the Chicago Bulls to six 1990s championships?", "Michael Jordan", null, ["Jordan"]],
  ["Which internet service was famous for the phrase You've got mail?", "AOL", null, ["America Online"]],
]);

add("Food & Drink", [
  ["What legume is the main ingredient in hummus?", "Chickpeas", null, ["chickpea", "garbanzo beans"]],
  ["What fruit is dried to make a prune?", "Plum", null, ["plums"]],
  ["Which cheese is traditionally used on pizza Margherita?", "Mozzarella"],
  ["What grain is used to make risotto?", "Rice", null, ["arborio rice"]],
  ["What is the Japanese name for green tea powder?", "Matcha"],
  ["Which herb is the base of traditional pesto Genovese?", "Basil"],
  ["What pastry is used for a classic profiterole?", "Choux pastry", null, ["choux"]],
  ["What Mexican dish folds a tortilla around a filling?", "Taco", null, ["tacos"]],
  ["Which spice gives many curries a yellow color?", "Turmeric"],
  ["What is tofu primarily made from?", "Soybeans", null, ["soy beans", "soya beans"]],
  ["What citrus fruit flavors Earl Grey tea?", "Bergamot"],
  ["Which country is the origin of paella?", "Spain"],
  ["What noodle dish is associated with Bologna?", "Tagliatelle al ragù", null, ["tagliatelle ragu", "tagliatelle"]],
  ["What nut is used in marzipan?", "Almond", null, ["almonds"]],
  ["Which sauce is made from egg yolk and oil as an emulsion?", "Mayonnaise", null, ["mayo"]],
  ["What is the primary spirit in a mojito?", "Rum", null, ["white rum"]],
  ["What dairy product is churned to make butter?", "Cream"],
  ["Which fruit has varieties called Hass and Fuerte?", "Avocado"],
  ["What is the Italian word for ice cream?", "Gelato"],
  ["Which bean is used to make chocolate?", "Cocoa bean", null, ["cacao", "cacao bean", "cacao beans", "cocoa", "cocoa beans"]],
]);

add("Animals", [
  ["What is the largest living animal?", "Blue whale"],
  ["What is a group of lions called?", "Pride", null, ["a pride"]],
  ["Which mammal lays eggs and has a duck-like bill?", "Platypus"],
  ["What is the fastest land animal?", "Cheetah"],
  ["Which bird is the largest living bird?", "Ostrich"],
  ["What do giant pandas mainly eat?", "Bamboo"],
  ["Which animal is known for changing color using chromatophores?", "Chameleon"],
  ["What is a baby goat called?", "Kid", null, ["a kid"]],
  ["Which marine mammal uses tusks and lives in the Arctic?", "Walrus"],
  ["How many legs does an arachnid have?", "Eight", null, ["8"]],
  ["Which animal has black skin beneath white fur?", "Polar bear"],
  ["What is the only mammal capable of sustained true flight?", "Bat", null, ["bats"]],
  ["Which insect makes honey?", "Honey bee", null, ["bee", "bees"]],
  ["What is a male deer commonly called?", "Stag", null, ["buck"]],
  ["Which amphibian begins life as a tadpole?", "Frog", null, ["frogs"]],
  ["What is the largest species of shark?", "Whale shark"],
  ["Which animal is famous for a pouch and powerful hind legs?", "Kangaroo"],
  ["What is a group of wolves called?", "Pack", null, ["a pack"]],
  ["Which flightless bird is native to New Zealand?", "Kiwi", null, ["kiwi bird"]],
  ["What do you call an animal active mainly at night?", "Nocturnal", null, ["nocturnal animal"]],
]);

add("Science", [
  ["What planet is known as the Red Planet?", "Mars"],
  ["What gas do plants absorb during photosynthesis?", "Carbon dioxide", null, ["CO2"]],
  ["What is the chemical symbol for gold?", "Au"],
  ["What force keeps planets in orbit?", "Gravity", null, ["gravitation"]],
  ["What is the center of an atom called?", "Nucleus", null, ["the nucleus"]],
  ["Which organ pumps blood around the human body?", "Heart", null, ["the heart"]],
  ["What is water's chemical formula?", "H2O", null, ["H₂O"]],
  ["What is the nearest star to Earth?", "The Sun", null, ["Sun"]],
  ["What process turns a liquid into a gas?", "Evaporation", null, ["vaporization"]],
  ["What scale measures mineral hardness?", "Mohs scale", null, ["Mohs"]],
  ["What particle has a negative electric charge?", "Electron", null, ["an electron"]],
  ["What is the largest organ of the human body?", "Skin", null, ["the skin"]],
  ["Which planet has the most prominent ring system?", "Saturn"],
  ["What branch of science studies living things?", "Biology"],
  ["What is the boiling point of water at sea level in Celsius?", "100", null, ["100°C", "100 degrees Celsius"]],
  ["What molecule carries genetic instructions in most organisms?", "DNA", null, ["deoxyribonucleic acid"]],
  ["What device records earthquakes?", "Seismograph", null, ["seismometer"]],
  ["Which blood cells carry oxygen?", "Red blood cells", null, ["erythrocytes"]],
  ["What is the speed of light commonly rounded to in kilometers per second?", "300000", null, ["300,000"]],
  ["What is the pH of a neutral solution at room temperature?", "7", null, ["seven"]],
]);

add("Sports", [
  ["How many players does one soccer team field at kickoff?", "Eleven", null, ["11"]],
  ["In tennis, what word means a score of zero?", "Love"],
  ["How many points is a basketball free throw worth?", "One", null, ["1"]],
  ["What sport uses a shuttlecock?", "Badminton"],
  ["How many rings are on the Olympic symbol?", "Five", null, ["5"]],
  ["What sport is played at Wimbledon?", "Tennis"],
  ["In baseball, how many strikes make an out?", "Three", null, ["3"]],
  ["What color jersey does the Tour de France leader wear?", "Yellow"],
  ["What country originated judo?", "Japan"],
  ["What is three under par on one golf hole called?", "Albatross", null, ["double eagle"]],
  ["How long is an Olympic swimming pool in meters?", "50", null, ["50 meters", "fifty"]],
  ["Which chess piece moves in an L shape?", "Knight", null, ["the knight"]],
  ["What sport features the pommel horse?", "Gymnastics"],
  ["How many points is a rugby union try worth?", "Five", null, ["5"]],
  ["What combat sport uses épée, foil, and sabre?", "Fencing"],
  ["What is the maximum score with one dart?", "60", null, ["sixty"]],
  ["In volleyball, how many players per team are on court?", "Six", null, ["6"]],
  ["What race is 42.195 kilometers long?", "Marathon", null, ["a marathon"]],
  ["What sport uses stones and brooms on ice?", "Curling"],
  ["Which martial art's name means gentle way?", "Judo"],
]);

add("General Knowledge", [
  ["What is the capital of Canada?", "Ottawa"], ["How many continents are commonly recognized?", "Seven", null, ["7"]],
  ["What is the longest river in South America?", "Amazon River", null, ["Amazon"]], ["Which language has the most native speakers?", "Mandarin Chinese", null, ["Mandarin"]],
  ["What is the currency of Japan?", "Yen", null, ["Japanese yen"]], ["Who painted the Mona Lisa?", "Leonardo da Vinci", null, ["da Vinci", "Leonardo"]],
  ["What is the smallest prime number?", "Two", null, ["2"]], ["Which ocean is the largest?", "Pacific Ocean", null, ["Pacific"]],
  ["What is the capital of New Zealand?", "Wellington"], ["Which country is shaped like a boot?", "Italy"],
  ["What is the Roman numeral for fifty?", "L"], ["Which artist sculpted the Renaissance statue David?", "Michelangelo", null, ["Michelangelo Buonarroti"]],
  ["What is the tallest mountain above sea level?", "Mount Everest", null, ["Everest"]], ["Which desert covers much of northern Africa?", "Sahara", null, ["Sahara Desert"]],
  ["What is the capital of Brazil?", "Brasília", null, ["Brasilia"]], ["Which metal is liquid at room temperature?", "Mercury"],
  ["How many sides does a dodecagon have?", "Twelve", null, ["12"]], ["What is the largest country by land area?", "Russia"],
  ["Which instrument has 88 keys on a standard model?", "Piano"], ["What is the study of maps called?", "Cartography"],
]);

add("Philippine History", [
  ["Who wrote the Kartilya ng Katipunan?", "Emilio Jacinto", null, ["Jacinto"]], ["What secret society did Andrés Bonifacio found?", "Katipunan", null, ["KKK"]],
  ["On what date is Philippine Independence Day celebrated?", "June 12", null, ["12 June"]], ["Who was the first President of the Philippine Republic?", "Emilio Aguinaldo", null, ["Aguinaldo"]],
  ["In what city was the 1898 declaration of independence proclaimed?", "Kawit", null, ["Kawit, Cavite"]], ["Who is known as the Great Plebeian?", "Andrés Bonifacio", null, ["Andres Bonifacio", "Bonifacio"]],
  ["What was the precolonial writing system used by many Tagalog speakers?", "Baybayin"], ["Who painted the Spoliarium?", "Juan Luna", null, ["Luna"]],
  ["What treaty ended the Spanish-American War and ceded the Philippines to the United States?", "Treaty of Paris", null, ["Treaty of Paris of 1898"]], ["Who was called the Sublime Paralytic?", "Apolinario Mabini", null, ["Mabini"]],
  ["What movement campaigned for reforms under Spanish rule?", "Propaganda Movement", null, ["Propaganda"]], ["Who founded La Liga Filipina?", "José Rizal", null, ["Jose Rizal", "Rizal"]],
  ["What newspaper was published by the Propaganda Movement in Spain?", "La Solidaridad"], ["Who was the first woman President of the Philippines?", "Corazon Aquino", null, ["Cory Aquino", "Aquino"]],
  ["What battle in 1521 resulted in the death of Ferdinand Magellan?", "Battle of Mactan", null, ["Mactan"]], ["Who led Filipino forces at the Battle of Mactan?", "Lapulapu", null, ["Lapu-Lapu", "Lapu Lapu"]],
  ["What constitution established the First Philippine Republic?", "Malolos Constitution", null, ["Constitution of Malolos"]], ["Where was José Rizal exiled?", "Dapitan", null, ["Dapitan City"]],
  ["Which three priests are collectively remembered as Gomburza?", "Gómez, Burgos, and Zamora", null, ["Gomez Burgos Zamora", "Mariano Gomez Jose Burgos Jacinto Zamora"]], ["What is the historic walled district of Manila called?", "Intramuros"],
]);

add("Philippine Geography", [
  ["What is the capital of the Philippines?", "Manila"], ["What is the largest Philippine island?", "Luzon"],
  ["What is the highest mountain in the Philippines?", "Mount Apo", null, ["Mt Apo", "Apo"]], ["Which island is famous for the Chocolate Hills?", "Bohol"],
  ["Which province contains the Banaue Rice Terraces?", "Ifugao"], ["What is the longest river in the Philippines?", "Cagayan River", null, ["Rio Grande de Cagayan"]],
  ["Which volcano is famous for its near-perfect cone?", "Mayon Volcano", null, ["Mayon"]], ["What sea lies west of the Philippine archipelago?", "West Philippine Sea", null, ["South China Sea"]],
  ["Which city is known as the Summer Capital of the Philippines?", "Baguio", null, ["Baguio City"]], ["What is the smallest Philippine province by land area?", "Batanes"],
  ["Which island group lies between Luzon and Mindanao?", "Visayas", null, ["the Visayas"]], ["What strait separates Samar and Leyte?", "San Juanico Strait", null, ["San Juanico"]],
  ["Which province is home to El Nido?", "Palawan"], ["Which lake is the largest in the Philippines?", "Laguna de Bay"],
  ["Which city is called the Queen City of the South?", "Cebu City", null, ["Cebu"]], ["What gulf borders Metro Manila?", "Manila Bay"],
  ["Which active volcano sits on an island within a lake in Batangas?", "Taal Volcano", null, ["Taal"]], ["Which province is Siargao part of?", "Surigao del Norte"],
  ["What channel separates Batanes from the Babuyan Islands?", "Balintang Channel", null, ["Balintang"]], ["Which river runs through Cagayan de Oro and is known for whitewater rafting?", "Cagayan de Oro River", null, ["Cagayan River"]],
]);

add("Filipino Culture & Language", [
  ["What Filipino value refers to communal unity and cooperation?", "Bayanihan"], ["What respectful words are commonly added when speaking to elders?", "Po and opo", null, ["po at opo", "po opo"]],
  ["What is the Filipino martial art also called Eskrima?", "Arnis", null, ["Kali"]], ["What woven sleeping mat is common in Filipino homes?", "Banig"],
  ["What giant lantern festival is held in San Fernando, Pampanga?", "Ligligan Parul", null, ["Giant Lantern Festival"]], ["What harvest festival in Lucban decorates houses with kiping?", "Pahiyas Festival", null, ["Pahiyas"]],
  ["What mythical creature is said to separate its upper body and fly at night?", "Manananggal"], ["What Filipino term describes the spirit of shared identity and empathy?", "Pakikipagkapwa", null, ["kapwa"]],
  ["What is the national language of the Philippines?", "Filipino"], ["What word means older sister in Filipino?", "Ate"],
  ["What word means older brother in Filipino?", "Kuya"], ["What bamboo dance involves stepping between moving poles?", "Tinikling"],
  ["What formal Filipino shirt is often made from piña fabric?", "Barong Tagalog", null, ["barong"]], ["What gesture places an elder's hand on one's forehead?", "Pagmamano", null, ["mano po", "mano"]],
  ["What star-shaped Christmas lantern is displayed in Filipino homes?", "Parol"], ["What Filipino serenade tradition is called?", "Harana"],
  ["What epic chant of the Ifugao is recognized by UNESCO?", "Hudhud", null, ["Hudhud chants"]], ["What is the Filipino term for a neighborhood community?", "Barangay"],
  ["What colorful festival in Iloilo honors the Santo Niño?", "Dinagyang Festival", null, ["Dinagyang"]], ["What festival in Aklan is known for soot-darkened faces and Ati costumes?", "Ati-Atihan", null, ["Ati Atihan"]],
]);

add("Filipino Entertainment", [
  ["Who is known as the King of Philippine Movies?", "Fernando Poe Jr.", null, ["FPJ", "Fernando Poe Junior"]], ["Who is known as the Asia's Songbird?", "Regine Velasquez", null, ["Regine Velasquez-Alcasid", "Regine"]],
  ["Which Filipino singer recorded Anak?", "Freddie Aguilar", null, ["Ka Freddie"]], ["What long-running noontime show introduced the segment Juan for All, All for Juan?", "Eat Bulaga", null, ["Eat Bulaga!"]],
  ["Who created the comic-book superhero Darna?", "Mars Ravelo", null, ["Ravelo"]], ["What is the superhero identity of Narda?", "Darna"],
  ["Which Filipino band recorded Eraserheads' hit Ang Huling El Bimbo?", "Eraserheads", null, ["The Eraserheads", "E-Heads"]], ["Who is known as the Megastar of Philippine entertainment?", "Sharon Cuneta", null, ["Sharon"]],
  ["Which singer is known as Mr. Pure Energy?", "Gary Valenciano", null, ["Gary V", "Gary Valenciano"]], ["Who directed the film Himala?", "Ishmael Bernal", null, ["Bernal"]],
  ["Which actress delivered the famous Walang himala line in Himala?", "Nora Aunor", null, ["Nora"]], ["What Filipino singing competition uses four coaches with turning chairs?", "The Voice of the Philippines", null, ["The Voice Philippines"]],
  ["Who composed the patriotic song Bayan Ko?", "Constancio de Guzman", null, ["Constancio de Guzmán", "de Guzman"]], ["Which OPM band recorded With a Smile?", "Eraserheads", null, ["The Eraserheads"]],
  ["Who is known as the Comedy King of the Philippines?", "Dolphy", null, ["Rodolfo Quizon"]], ["Which fantasy TV series features the kingdoms Lireo, Sapiro, Hathoria, and Adamya?", "Encantadia"],
  ["What is the title of Lea Salonga's character in Miss Saigon?", "Kim"], ["Which Filipina singer provided the singing voices of Jasmine and Mulan?", "Lea Salonga", null, ["Lea"]],
  ["What 2015 romantic film paired Enrique Gil and Liza Soberano in Baguio?", "Just the Way You Are"], ["Which Filipino folk-rock band recorded Himig Natin?", "Juan de la Cruz Band", null, ["Juan de la Cruz"]],
]);

add("Music", [
  ["Who released the album Thriller?", "Michael Jackson", null, ["MJ"]],
  ["Who was the lead singer of Queen?", "Freddie Mercury", null, ["Freddie"]],
  ["Which English city did The Beatles form in?", "Liverpool"],
  ["How many numbered symphonies did Beethoven complete?", "Nine", null, ["9"]],
  ["How many keys are on a standard modern piano?", "88", null, ["eighty-eight", "88 keys"]],
  ["Which instrument family includes the violin, viola, and cello?", "Strings", null, ["string family", "string instruments"]],
  ["Which group launched Beyoncé to fame?", "Destiny's Child", null, ["Destinys Child"]],
  ["What number is the title of Adele's second studio album?", "21", null, ["twenty-one"]],
  ["Which Jamaican musician is strongly associated with reggae and the Wailers?", "Bob Marley", null, ["Marley"]],
  ["Who composed The Four Seasons?", "Antonio Vivaldi", null, ["Vivaldi"]],
  ["What other name is commonly used for the treble clef?", "G clef", null, ["G-clef"]],
  ["Which instrument did Louis Armstrong famously play?", "Trumpet", null, ["the trumpet"]],
  ["Which country did the group BTS form in?", "South Korea", null, ["Korea"]],
  ["What nickname is commonly used for Taylor Swift fans?", "Swifties", null, ["Swiftie"]],
  ["Who invented the saxophone?", "Adolphe Sax", null, ["Sax"]],
  ["Who composed the opera Carmen?", "Georges Bizet", null, ["Bizet"]],
  ["Which singer is known as the Material Girl?", "Madonna"],
  ["What is the lowest standard adult male singing voice?", "Bass", null, ["bass voice"]],
  ["Which band recorded Hotel California?", "Eagles", null, ["The Eagles"]],
  ["Which singer released Purple Rain?", "Prince"],
]);

add("TV Shows", [
  ["What coffee shop does the Friends group regularly visit?", "Central Perk", "Friends"],
  ["What is the name of Ross's pet monkey?", "Marcel", "Friends"],
  ["What song is Phoebe best known for performing?", "Smelly Cat", "Friends"],
  ["What is Chandler's surname?", "Bing", "Friends", ["Chandler Bing"]],
  ["What is Joey Tribbiani's profession?", "Actor", "Friends", ["an actor"]],
  ["What is Monica Geller's profession?", "Chef", "Friends", ["a chef"]],
  ["What is Rachel's surname?", "Green", "Friends", ["Rachel Green", "Greene"]],
  ["What is Ross Geller's academic profession?", "Paleontologist", "Friends", ["a paleontologist"]],
  ["Who is Monica's brother?", "Ross Geller", "Friends", ["Ross"]],
  ["Which Friend has an identical twin named Ursula?", "Phoebe Buffay", "Friends", ["Phoebe"]],

  ["What is Meredith's surname in Grey's Anatomy?", "Grey", "Grey's Anatomy", ["Meredith Grey"]],
  ["What is the hospital called at the beginning of Grey's Anatomy?", "Seattle Grace Hospital", "Grey's Anatomy", ["Seattle Grace"]],
  ["What nickname is given to Derek Shepherd?", "McDreamy", "Grey's Anatomy"],
  ["What surgical specialty does Cristina Yang pursue?", "Cardiothoracic surgery", "Grey's Anatomy", ["cardiothoracic", "cardio"]],
  ["Who created Grey's Anatomy?", "Shonda Rhimes", "Grey's Anatomy", ["Shonda"]],
  ["What is Dr. Bailey's first name?", "Miranda", "Grey's Anatomy", ["Miranda Bailey"]],
  ["Which surgical specialty does Alex Karev eventually choose?", "Pediatric surgery", "Grey's Anatomy", ["pediatrics", "pediatric surgeon"]],
  ["Who serves as chief of surgery when the series begins?", "Richard Webber", "Grey's Anatomy", ["Webber"]],
  ["What is Callie Torres's surgical specialty?", "Orthopedic surgery", "Grey's Anatomy", ["orthopedics", "orthopedic surgeon"]],
  ["What is the name of Meredith Grey's surgeon mother?", "Ellis Grey", "Grey's Anatomy", ["Ellis"]],

  ["In which fictional Texas town does Young Sheldon begin?", "Medford", "Young Sheldon", ["Medford, Texas"]],
  ["What is Sheldon's twin sister called?", "Missy", "Young Sheldon", ["Melissa Cooper", "Missy Cooper"]],
  ["What is Sheldon's older brother called?", "Georgie", "Young Sheldon", ["George Cooper Jr.", "George Jr"]],
  ["What is Sheldon's mother's name?", "Mary Cooper", "Young Sheldon", ["Mary"]],
  ["What is Sheldon's father's name?", "George Cooper Sr.", "Young Sheldon", ["George Sr", "George Cooper"]],
  ["What does Sheldon call his grandmother?", "Meemaw", "Young Sheldon", ["Connie", "Connie Tucker"]],
  ["Which pastor leads the Cooper family's church?", "Pastor Jeff", "Young Sheldon", ["Jeff Difford"]],
  ["Which university does Sheldon attend before moving to California?", "East Texas Tech", "Young Sheldon", ["East Texas Technical University"]],
  ["What subject is Sheldon exceptionally gifted at?", "Physics", "Young Sheldon"],
  ["Which actor plays young Sheldon?", "Iain Armitage", "Young Sheldon", ["Armitage"]],

  ["Who is Sheldon's roommate at the start of The Big Bang Theory?", "Leonard Hofstadter", "The Big Bang Theory", ["Leonard"]],
  ["What is the first name of Leonard and Sheldon's neighbor?", "Penny", "The Big Bang Theory"],
  ["What word does Sheldon use after many of his jokes?", "Bazinga", "The Big Bang Theory"],
  ["What is Sheldon's scientific field?", "Theoretical physics", "The Big Bang Theory", ["physics", "theoretical physicist"]],
  ["What kind of engineer is Howard Wolowitz?", "Aerospace engineer", "The Big Bang Theory", ["aerospace engineering"]],
  ["What is Raj Koothrappali's scientific field?", "Astrophysics", "The Big Bang Theory", ["astrophysicist"]],
  ["What is Amy Farrah Fowler's scientific field?", "Neurobiology", "The Big Bang Theory", ["neuroscience", "neurobiologist"]],
  ["Who owns the comic book store?", "Stuart Bloom", "The Big Bang Theory", ["Stuart"]],
  ["What frequently broken feature forces the characters to use the stairs?", "Elevator", "The Big Bang Theory", ["the elevator"]],
  ["At which university do Sheldon and Leonard work?", "Caltech", "The Big Bang Theory", ["California Institute of Technology"]],

  ["Who narrates most of How I Met Your Mother?", "Ted Mosby", "How I Met Your Mother", ["Ted"]],
  ["What is the Mother's name?", "Tracy McConnell", "How I Met Your Mother", ["Tracy"]],
  ["Which character is known for wearing suits?", "Barney Stinson", "How I Met Your Mother", ["Barney"]],
  ["What book contains Barney's dating strategies?", "The Playbook", "How I Met Your Mother", ["Playbook"]],
  ["What pub does the group regularly visit?", "MacLaren's Pub", "How I Met Your Mother", ["MacLarens", "MacLaren's"]],
  ["Which country is Robin Scherbatsky from?", "Canada", "How I Met Your Mother"],
  ["What is Marshall Eriksen's profession?", "Lawyer", "How I Met Your Mother", ["an attorney", "attorney"]],
  ["What is Lily Aldrin's profession at the start of the series?", "Kindergarten teacher", "How I Met Your Mother", ["teacher"]],
  ["What object becomes a symbol connected to the Mother?", "Yellow umbrella", "How I Met Your Mother", ["the yellow umbrella"]],
  ["What was Robin's Canadian pop-star name?", "Robin Sparkles", "How I Met Your Mother"],
]);

add("Filipino Food & Drink", [
  ["What Filipino dessert mixes shaved ice with milk and assorted sweets?", "Halo-halo", null, ["halo halo"]],
  ["What Filipino soup is known for its distinctly sour broth?", "Sinigang"],
  ["Which fruit is a common traditional souring ingredient for sinigang?", "Tamarind", null, ["sampalok"]],
  ["What Filipino celebration dish is a whole roasted pig?", "Lechon", null, ["lechon baboy"]],
  ["What Filipino snack is a fried or fresh spring roll?", "Lumpia", null, ["spring roll", "spring rolls"]],
  ["What general Filipino term refers to noodle dishes?", "Pancit", null, ["pansit"]],
  ["Which Filipino stew is traditionally served with a thick peanut sauce?", "Kare-kare", null, ["kare kare"]],
  ["What fermented fish or shrimp paste commonly accompanies kare-kare?", "Bagoong", null, ["shrimp paste", "fish paste"]],
  ["What small Philippine citrus fruit is commonly used for juice and seasoning?", "Calamansi", null, ["kalamansi", "Philippine lime"]],
  ["What purple yam is used in many Filipino desserts?", "Ube", null, ["purple yam"]],
  ["What Filipino rice cake is traditionally baked in a clay pot lined with banana leaves?", "Bibingka"],
  ["What small Filipino steamed rice cake is commonly eaten as a snack?", "Puto"],
  ["What street food combines silken tofu, arnibal, and sago pearls?", "Taho"],
  ["What Filipino delicacy is a fertilized duck egg cooked in its shell?", "Balut"],
  ["Which sizzling chopped-pork dish originated in Pampanga?", "Sisig"],
  ["Which grilled chicken dish is especially associated with Bacolod?", "Chicken inasal", null, ["inasal", "inasal na manok"]],
  ["What spicy Bicolano dish combines pork, chilies, and coconut milk?", "Bicol Express", null, ["Bikol Express"]],
  ["What Bicolano dish cooks dried taro leaves in coconut milk?", "Laing"],
  ["What Filipino preparation cures raw seafood with vinegar or citrus?", "Kinilaw", null, ["kilawin"]],
  ["What Filipino refreshment combines tapioca pearls and jelly in a sweet drink?", "Sago't gulaman", null, ["sago at gulaman", "sago gulaman"]],
]);

add("Japan Culture", [
  ["What is the traditional Japanese tea ceremony commonly called?", "Chanoyu", null, ["chado", "sadō", "sado", "the way of tea"]],
  ["What traditional Japanese robe wraps left over right and is secured with an obi?", "Kimono"],
  ["What lightweight casual robe is often worn at summer festivals and hot springs?", "Yukata"],
  ["What is the Japanese custom of viewing cherry blossoms?", "Hanami", null, ["flower viewing"]],
  ["What gate commonly marks the entrance to a Shinto shrine?", "Torii", null, ["torii gate"]],
  ["What woven straw mats traditionally cover Japanese room floors?", "Tatami", null, ["tatami mats"]],
  ["What is the Japanese art of paper folding?", "Origami"],
  ["What is the Japanese art of flower arrangement?", "Ikebana", null, ["kado", "kadō"]],
  ["What is the highest rank in professional sumo?", "Yokozuna"],
  ["What three-line poetry form traditionally follows a 5-7-5 sound pattern?", "Haiku"],
  ["What Japanese theater form is known for elaborate makeup and stylized performance?", "Kabuki"],
  ["What classical Japanese theater form uses masks and restrained movement?", "Noh", null, ["Nō", "Noh theater"]],
  ["What Japanese word refers to comics or graphic narratives?", "Manga"],
  ["What Japanese term is used for animation?", "Anime"],
  ["What is a Japanese hot-spring bath called?", "Onsen", null, ["hot spring"]],
  ["What paper fortune can visitors draw at Japanese shrines and temples?", "Omikuji", null, ["o-mikuji"]],
  ["What wooden plaque is used to write wishes at a Shinto shrine?", "Ema", null, ["ema plaque"]],
  ["What bean-throwing ritual is performed during Setsubun?", "Mamemaki", null, ["bean throwing"]],
  ["What star festival celebrates the meeting of Orihime and Hikoboshi?", "Tanabata", null, ["Star Festival"]],
  ["What boxed assortment of special dishes is traditionally eaten at Japanese New Year?", "Osechi", null, ["osechi ryori", "osechi-ryōri"]],
]);

add("Philippine Literature", [
  ["Who wrote Noli Me Tángere?", "José Rizal", null, ["Jose Rizal", "Rizal"]],
  ["What novel is the sequel to Noli Me Tángere?", "El Filibusterismo", null, ["El Fili"]],
  ["Who wrote Florante at Laura?", "Francisco Balagtas", null, ["Francisco Baltazar", "Balagtas", "Baltazar"]],
  ["Who is the traditionally listed author of Ibong Adarna?", "Anonymous", null, ["unknown", "unknown author", "anon"]],
  ["What Ilocano epic follows the hero Lam-ang?", "Biag ni Lam-ang", null, ["Biag ni Lam Ang"]],
  ["What Ifugao epic chants are traditionally performed during harvest and funerals?", "Hudhud", null, ["Hudhud chants"]],
  ["What Maranao epic recounts the adventures of Prince Bantugan?", "Darangen", null, ["the Darangen"]],
  ["Who wrote the short story Dead Stars?", "Paz Márquez-Benítez", null, ["Paz Marquez Benitez", "Marquez-Benitez"]],
  ["Who wrote Footnote to Youth?", "José García Villa", null, ["Jose Garcia Villa", "Garcia Villa"]],
  ["Who wrote How My Brother Leon Brought Home a Wife?", "Manuel Arguilla", null, ["Manuel E. Arguilla", "Arguilla"]],
  ["Who wrote The Woman Who Had Two Navels?", "Nick Joaquin", null, ["Joaquin"]],
  ["Who wrote Mga Ibong Mandaragit?", "Amado V. Hernandez", null, ["Amado Hernandez", "Hernandez"]],
  ["Who wrote the novel Dekada '70?", "Lualhati Bautista", null, ["Bautista"]],
  ["Who wrote Smaller and Smaller Circles?", "F. H. Batacan", null, ["FH Batacan", "Felisa Batacan", "Batacan"]],
  ["Who wrote Banaag at Sikat?", "Lope K. Santos", null, ["Lope Santos", "Santos"]],
  ["Who wrote America Is in the Heart?", "Carlos Bulosan", null, ["Bulosan"]],
  ["Who wrote Without Seeing the Dawn?", "Stevan Javellana", null, ["Javellana"]],
  ["Who wrote the novel Po-on?", "F. Sionil José", null, ["F Sionil Jose", "Francisco Sionil Jose", "Sionil Jose"]],
  ["Who created the stories Mga Kuwento ni Lola Basyang?", "Severino Reyes", null, ["Reyes"]],
  ["Which poet is known as the Prince of Tagalog Poets?", "Francisco Balagtas", null, ["Francisco Baltazar", "Balagtas", "Baltazar"]],
]);

add("Books", [
  ["Who wrote The Picture of Dorian Gray?", "Oscar Wilde", null, ["Wilde"]],
  ["Who wrote The Great Gatsby?", "F. Scott Fitzgerald", null, ["F Scott Fitzgerald", "Fitzgerald"]],
  ["Who wrote Don Quixote?", "Miguel de Cervantes", null, ["Cervantes"]],
  ["Who wrote Alice's Adventures in Wonderland?", "Lewis Carroll", null, ["Carroll"]],
  ["Who wrote Frankenstein?", "Mary Shelley", null, ["Shelley"]],
  ["Who narrates The Catcher in the Rye?", "Holden Caulfield", null, ["Holden"]],
  ["Which pig becomes the leader in Animal Farm?", "Napoleon"],
  ["Who wrote Dracula?", "Bram Stoker", null, ["Stoker"]],
  ["Who wrote One Hundred Years of Solitude?", "Gabriel García Márquez", null, ["Gabriel Garcia Marquez", "Garcia Marquez", "Marquez"]],
  ["Who wrote Les Misérables?", "Victor Hugo", null, ["Hugo"]],
]);

add("The '90s", [
  ["In what year was the Linux kernel first released?", "1991"],
  ["In what year did Sony release the original PlayStation in Japan?", "1994"],
  ["In what year did Toy Story premiere?", "1995"],
  ["In what year did DVD players first go on sale in Japan?", "1996"],
  ["In what year did the film Titanic premiere?", "1997"],
  ["In what year did the music-sharing service Napster launch?", "1999"],
  ["Which fuzzy electronic toy became a holiday craze in 1998?", "Furby"],
  ["Which collectible plush toys became a major 1990s craze?", "Beanie Babies", null, ["Beanie Baby"]],
  ["Which TV series followed FBI agents Mulder and Scully?", "The X-Files", null, ["X-Files", "X Files"]],
  ["Which franchise used the English slogan Gotta catch 'em all?", "Pokémon", null, ["Pokemon"]],
]);

add("Food & Drink", [
  ["What is the world's most expensive spice by weight?", "Saffron"],
  ["What fruit is the main ingredient in guacamole?", "Avocado"],
  ["What part of an egg is whipped to make a basic meringue?", "Egg white", null, ["egg whites"]],
  ["What grain is fermented to make Japanese sake?", "Rice"],
  ["Which country is feta cheese traditionally associated with?", "Greece"],
  ["What fried Middle Eastern food is commonly made from chickpeas or fava beans?", "Falafel"],
  ["What small, concentrated coffee originated in Italy?", "Espresso"],
  ["What vegetable is fermented to make sauerkraut?", "Cabbage"],
  ["What dairy ingredient forms the base of tzatziki?", "Yogurt", null, ["yoghurt"]],
  ["Vanilla flavoring comes from the pods of what flowering plant family?", "Orchid", null, ["orchids", "orchid family"]],
]);

add("Animals", [
  ["How many hearts does an octopus have?", "Three", null, ["3"]],
  ["Which land animal has the longest pregnancy, lasting about 22 months?", "Elephant", null, ["African elephant"]],
  ["What amphibian is famous for retaining its external gills as an adult?", "Axolotl"],
  ["What is a group of crows called?", "Murder", null, ["a murder"]],
  ["A narwhal's tusk is actually an enlarged form of what?", "Tooth", null, ["a tooth"]],
  ["Which animal is the largest living primate?", "Eastern gorilla", null, ["gorilla"]],
  ["What is a baby kangaroo called?", "Joey"],
  ["Which bird can fly backward?", "Hummingbird", null, ["hummingbirds"]],
  ["Which mammal has fingerprints so similar to humans that they can be confused at a crime scene?", "Koala", null, ["koalas"]],
  ["What is the largest living reptile?", "Saltwater crocodile", null, ["saltwater croc"]],
]);

add("Science", [
  ["What is the SI unit of force?", "Newton", null, ["newtons"]],
  ["What is the atomic number of oxygen?", "Eight", null, ["8"]],
  ["What is the largest planet in the Solar System?", "Jupiter"],
  ["Which organelle is often called the powerhouse of the cell?", "Mitochondrion", null, ["mitochondria"]],
  ["What theory explains the movement of Earth's large crustal plates?", "Plate tectonics", null, ["the theory of plate tectonics"]],
  ["What temperature is absolute zero on the Kelvin scale?", "Zero kelvin", null, ["0 kelvin", "0 K", "zero K"]],
  ["Which vitamin can the human body produce when skin is exposed to sunlight?", "Vitamin D"],
  ["Which blood type is commonly called the universal red-cell donor?", "O negative", null, ["O-negative", "O neg"]],
  ["Which part of a plant cell carries out photosynthesis?", "Chloroplast", null, ["chloroplasts"]],
  ["What instrument is used to view objects too small for the unaided eye?", "Microscope"],
]);

add("Sports", [
  ["How many bases must a baseball player touch to complete a home run?", "Four", null, ["4"]],
  ["How many points is an NFL touchdown worth before the extra-point attempt?", "Six", null, ["6"]],
  ["How many wooden stumps make up a cricket wicket?", "Three", null, ["3"]],
  ["What flag signals the finish of a motor race?", "Checkered flag", null, ["chequered flag"]],
  ["Which winter sport combines cross-country skiing and rifle shooting?", "Biathlon"],
  ["How high is a regulation basketball hoop in feet?", "Ten", null, ["10", "10 feet"]],
  ["What abbreviation means a knockout in boxing?", "KO", null, ["K.O.", "knockout"]],
  ["How many events are in a pentathlon?", "Five", null, ["5"]],
  ["How many points normally win a table-tennis game if the player leads by two?", "Eleven", null, ["11"]],
  ["What object is struck in ice hockey instead of a ball?", "Puck", null, ["hockey puck"]],
]);

add("General Knowledge", [
  ["What is the capital of Australia?", "Canberra"],
  ["In which city is the Nobel Peace Prize awarded?", "Oslo"],
  ["What number is pi commonly rounded to two decimal places?", "3.14"],
  ["What is the name of the bell inside London's Elizabeth Tower?", "Big Ben"],
  ["Which country has a maple leaf on its national flag?", "Canada"],
  ["Who is the Greek god of the sea?", "Poseidon"],
  ["In which country is the Taj Mahal?", "India"],
  ["What is the capital of Spain?", "Madrid"],
  ["How many squares are on a standard chessboard?", "Sixty-four", null, ["64"]],
  ["Which inventor is associated with Europe's movable-type printing press?", "Johannes Gutenberg", null, ["Gutenberg"]],
]);

add("Philippine History", [
  ["Who served as the first President of the Philippine Commonwealth?", "Manuel L. Quezon", null, ["Manuel Quezon", "Quezon"]],
  ["What 1986 uprising is also called the EDSA Revolution?", "People Power Revolution", null, ["People Power", "EDSA People Power Revolution", "EDSA Revolution"]],
  ["At what church did the Malolos Congress convene in 1898?", "Barasoain Church", null, ["Barasoain"]],
  ["What 1897 assembly elected Emilio Aguinaldo president of a revolutionary government?", "Tejeros Convention", null, ["Tejeros Assembly"]],
  ["Who was the first President of the Philippine Senate?", "Manuel L. Quezon", null, ["Manuel Quezon", "Quezon"]],
  ["What forced march followed the fall of Bataan in 1942?", "Bataan Death March", null, ["the Bataan Death March"]],
  ["Who edited the revolutionary newspaper La Independencia?", "Antonio Luna", null, ["General Antonio Luna", "Luna"]],
  ["What 1935 charter established the Philippine Commonwealth?", "1935 Constitution", null, ["the 1935 Constitution", "Constitution of 1935"]],
  ["Which American general famously promised to return to the Philippines during World War II?", "Douglas MacArthur", null, ["General MacArthur", "MacArthur"]],
  ["Which Filipina revolutionary is remembered as the Mother of Biak-na-Bato?", "Trinidad Tecson", null, ["Tecson"]],
]);

add("Philippine Geography", [
  ["Which province is known as the Island Born of Fire?", "Camiguin"],
  ["Maria Cristina Falls is located in which city?", "Iligan City", null, ["Iligan"]],
  ["The Hundred Islands National Park is in which province?", "Pangasinan"],
  ["The Hinatuan Enchanted River is in which province?", "Surigao del Sur"],
  ["Which city is the largest in the Philippines by land area?", "Davao City", null, ["Davao"]],
  ["What river connects Laguna de Bay to Manila Bay?", "Pasig River", null, ["the Pasig River"]],
  ["What is the highest mountain on Luzon?", "Mount Pulag", null, ["Mt. Pulag", "Mt Pulag"]],
  ["Which province is home to the surfing destination Baler?", "Aurora"],
  ["Which sea contains the Tubbataha Reefs Natural Park?", "Sulu Sea", null, ["the Sulu Sea"]],
  ["Which province contains the underground river at Puerto Princesa?", "Palawan"],
]);

add("Filipino Culture & Language", [
  ["What Maranao dance is performed with fans between crossed bamboo poles?", "Singkil"],
  ["What Philippine gong-chime ensemble is associated with Mindanao and the Sulu Archipelago?", "Kulintang"],
  ["What fiber used in formal Filipino clothing comes from pineapple leaves?", "Piña", null, ["Pina", "pineapple fiber"]],
  ["What traditional Filipino house is also called a nipa hut?", "Bahay kubo", null, ["nipa hut"]],
  ["What wide-brimmed traditional Filipino hat is often made from rattan or reeds?", "Salakot"],
  ["What decorated public-transport vehicle became a Filipino cultural icon?", "Jeepney", null, ["jeepneys"]],
  ["What traditional Filipino love-song genre is known for poetic Tagalog lyrics?", "Kundiman"],
  ["What nine-day series of dawn Masses is held before Christmas?", "Simbang Gabi", null, ["Misa de Gallo"]],
  ["What May procession commemorates the finding of the Holy Cross?", "Santacruzan"],
  ["What folk dance uses fans or handkerchiefs to portray courtship?", "Cariñosa", null, ["Carinosa"]],
]);

add("Filipino Entertainment", [
  ["Which director made the films Manila in the Claws of Light and Insiang?", "Lino Brocka", null, ["Brocka"]],
  ["Who is known as the Popstar Royalty of the Philippines?", "Sarah Geronimo", null, ["Sarah G", "Geronimo"]],
  ["Who played General Antonio Luna in the film Heneral Luna?", "John Arcilla", null, ["Arcilla"]],
  ["What is the name of the detective heroine in the Filipino comic series Trese?", "Alexandra Trese", null, ["Trese"]],
  ["Which band recorded the OPM song Harana?", "Parokya ni Edgar", null, ["Parokya"]],
  ["Which band recorded the song 214?", "Rivermaya"],
  ["Which singing group launched Smokey Mountain's hit Kailan?", "Smokey Mountain"],
  ["Who is known as the Queen of Soul in Philippine music?", "Jaya", null, ["Jaya Ramsey"]],
  ["What is the name of Coco Martin's character in FPJ's Ang Probinsyano?", "Cardo Dalisay", null, ["Ricardo Dalisay", "Cardo"]],
  ["Who directed Four Sisters and a Wedding?", "Cathy Garcia-Molina", null, ["Cathy Garcia Molina", "Garcia-Molina"]],
]);

add("Music", [
  ["Who is the lead singer of The Rolling Stones?", "Mick Jagger", null, ["Jagger"]],
  ["Which band recorded Smells Like Teen Spirit?", "Nirvana"],
  ["What is Lady Gaga's birth name?", "Stefani Germanotta", null, ["Stefani Joanne Angelina Germanotta"]],
  ["Which Caribbean country is Rihanna from?", "Barbados"],
  ["How many strings does a standard cello have?", "Four", null, ["4"]],
  ["What musical tempo marking means slow and stately?", "Adagio"],
  ["Which country did ABBA form in?", "Sweden"],
  ["Which country is rapper Drake from?", "Canada"],
  ["What is Eminem's real name?", "Marshall Mathers", null, ["Marshall Bruce Mathers III", "Marshall Bruce Mathers"]],
  ["Which composer is especially known for piano nocturnes and polonaises?", "Frédéric Chopin", null, ["Frederic Chopin", "Chopin"]],
]);

add("Filipino Food & Drink", [
  ["What Filipino stew commonly braises meat in vinegar, soy sauce, garlic, and spices?", "Adobo"],
  ["What is the Filipino name for local sausage, often served for breakfast?", "Longganisa", null, ["longanisa"]],
  ["What chocolate rice porridge is often paired with dried salted fish?", "Champorado"],
  ["What snack wraps banana and sugar in a spring-roll wrapper before frying?", "Turon", null, ["banana turon"]],
  ["What sweet coiled bread is topped with butter, sugar, and often cheese?", "Ensaymada", null, ["ensaimada"]],
  ["What chilled dessert combines young coconut, pandan jelly, and cream?", "Buko pandan", null, ["buko pandan salad"]],
  ["What Filipino ginger tea is traditionally served hot?", "Salabat", null, ["ginger tea"]],
  ["What strong coffee variety is associated with Batangas?", "Kapeng barako", null, ["barako coffee", "barako"]],
  ["What savory stew is made with pork blood and vinegar?", "Dinuguan"],
  ["What noodle dish is topped with an orange shrimp sauce, egg, and crushed chicharon?", "Pancit palabok", null, ["palabok"]],
]);

add("Japan Culture", [
  ["What is Japan's indigenous religion called?", "Shinto", null, ["Shintoism"]],
  ["What is Japan's high-speed railway commonly called?", "Shinkansen", null, ["bullet train"]],
  ["What is the Japanese art of growing miniature trees in containers?", "Bonsai"],
  ["What repair art highlights broken pottery seams with lacquer and powdered gold?", "Kintsugi"],
  ["What traditional Japanese bedding is laid directly on tatami floors?", "Futon", null, ["Japanese futon"]],
  ["What formal kneeling posture involves sitting on one's heels?", "Seiza"],
  ["What Japanese word means a traditional festival?", "Matsuri", null, ["festival"]],
  ["What round doll is used as a symbol of perseverance and goal-setting?", "Daruma", null, ["Daruma doll"]],
  ["What traditional Japanese inn is called?", "Ryokan", null, ["Japanese inn"]],
  ["What carp is commonly kept in decorative Japanese ponds?", "Koi", null, ["koi carp"]],
]);

add("Philippine Literature", [
  ["Who wrote the short story The Mats?", "Francisco Arcellana", null, ["Arcellana"]],
  ["Who wrote the short story The Wedding Dance?", "Amador Daguio", null, ["Amador T. Daguio", "Daguio"]],
  ["Who wrote My Father Goes to Court?", "Carlos Bulosan", null, ["Bulosan"]],
  ["Who wrote the short story May Day Eve?", "Nick Joaquin", null, ["Joaquin"]],
  ["Who wrote the novel Gapo?", "Lualhati Bautista", null, ["Bautista"]],
  ["Who wrote the novel Ilustrado?", "Miguel Syjuco", null, ["Syjuco"]],
  ["Who wrote State of War?", "Ninotchka Rosca", null, ["Rosca"]],
  ["Who wrote The Bread of Salt?", "N. V. M. Gonzalez", null, ["NVM Gonzalez", "Nestor Vicente Madali Gonzalez", "Gonzalez"]],
  ["Who wrote the novel Ermita?", "Nick Joaquin", null, ["Joaquin"]],
  ["Which Filipino poet also writes under the pen name Rio Alma?", "Virgilio Almario", null, ["Almario"]],
]);

// Theme expansion: every movie/book/TV theme grows from 10 to 30 questions.
add("Movies", [
  ["Who trains Luke Skywalker on Dagobah?", "Yoda", "Star Wars"],
  ["What is the Rebel Alliance's ice planet base called?", "Hoth", "Star Wars"],
  ["Which beeping astromech droid frequently accompanies Luke?", "R2-D2", "Star Wars", ["R2D2"]],
  ["What is Darth Vader's home planet?", "Tatooine", "Star Wars"],
  ["Who mentors Rey in The Last Jedi?", "Luke Skywalker", "Star Wars", ["Luke"]],
  ["What order of Force-wielding peacekeepers does Luke join?", "Jedi", "Star Wars"],
  ["What is the Galactic Empire's capital planet?", "Coruscant", "Star Wars"],
  ["What weapon do Jedi traditionally wield?", "Lightsaber", "Star Wars"],
  ["Who is revealed to be Kylo Ren's father?", "Han Solo", "Star Wars"],
  ["What creature does Luke fight in Jabba's palace pit?", "Rancor", "Star Wars"],
  ["In what year did the original Star Wars film premiere?", "1977", "Star Wars"],
  ["Who directed the original 1977 Star Wars film?", "George Lucas", "Star Wars"],
  ["What is the name of the Empire's planet-destroying superweapon?", "Death Star", "Star Wars"],
  ["Who is Anakin Skywalker's Jedi Master?", "Obi-Wan Kenobi", "Star Wars", ["Obi Wan Kenobi", "Obi-Wan"]],
  ["Which droid belongs to Resistance pilot Poe Dameron?", "BB-8", "Star Wars", ["BB8"]],
  ["What is Palpatine's secret identity as a Dark Lord of the Sith?", "Darth Sidious", "Star Wars"],
  ["Who voices Darth Vader?", "James Earl Jones", "Star Wars"],
  ["What is Finn's stormtrooper designation number?", "FN-2187", "Star Wars", ["FN2187"]],
  ["Which planet does Padmé Amidala serve as queen?", "Naboo", "Star Wars"],
  ["Jabba the Hutt belongs to which slug-like alien species?", "Hutt", "Star Wars", ["Hutts"]],

  ["What is Peter Parker's superhero name?", "Spider-Man", "Marvel Cinematic Universe", ["Spiderman"]],
  ["What company does Tony Stark run?", "Stark Industries", "Marvel Cinematic Universe"],
  ["What is Steve Rogers' superhero alias?", "Captain America", "Marvel Cinematic Universe"],
  ["Which Infinity Stone was hidden inside the Aether?", "Reality Stone", "Marvel Cinematic Universe"],
  ["What is the name of Thor's home realm?", "Asgard", "Marvel Cinematic Universe"],
  ["Who is Thor's adoptive brother?", "Loki", "Marvel Cinematic Universe"],
  ["What spy organization does Nick Fury lead?", "S.H.I.E.L.D.", "Marvel Cinematic Universe", ["SHIELD"]],
  ["What is Scott Lang's superhero name?", "Ant-Man", "Marvel Cinematic Universe", ["Antman"]],
  ["Which villain seeks to collect all six Infinity Stones?", "Thanos", "Marvel Cinematic Universe"],
  ["Who succeeds T'Challa as Black Panther in Wakanda Forever?", "Shuri", "Marvel Cinematic Universe"],
  ["What is Doctor Strange's profession before becoming a sorcerer?", "Surgeon", "Marvel Cinematic Universe"],
  ["Which Guardians of the Galaxy member is a talking raccoon?", "Rocket", "Marvel Cinematic Universe"],
  ["What is Star-Lord's real name?", "Peter Quill", "Marvel Cinematic Universe"],
  ["Which Infinity Stone is embedded in the Eye of Agamotto?", "Time Stone", "Marvel Cinematic Universe"],
  ["What is Hawkeye's real name?", "Clint Barton", "Marvel Cinematic Universe"],
  ["What herb gives the Black Panther enhanced powers?", "Heart-Shaped Herb", "Marvel Cinematic Universe"],
  ["In what year did the first Iron Man film release?", "2008", "Marvel Cinematic Universe"],
  ["Which directing duo made Avengers: Endgame?", "The Russo Brothers", "Marvel Cinematic Universe", ["Russo Brothers", "The Russos"]],
  ["What is the name of Tony Stark's AI assistant?", "J.A.R.V.I.S.", "Marvel Cinematic Universe", ["JARVIS"]],
  ["What is Sam Wilson's superhero name before becoming Captain America?", "Falcon", "Marvel Cinematic Universe"],

  ["What is the name of Ariel's crab friend in The Little Mermaid?", "Sebastian", "Disney & Pixar"],
  ["What is the name of Elsa's kingdom in Frozen?", "Arendelle", "Disney & Pixar"],
  ["Who is Woody's cowgirl friend in Toy Story?", "Jessie", "Disney & Pixar"],
  ["What is the name of the boy raised by wolves in The Jungle Book?", "Mowgli", "Disney & Pixar"],
  ["Who is Belle's love interest, cursed to be a monster?", "Beast", "Disney & Pixar"],
  ["Which Pixar film follows a boy named Miguel into the Land of the Dead?", "Coco", "Disney & Pixar"],
  ["What is the sea witch villain called in The Little Mermaid?", "Ursula", "Disney & Pixar"],
  ["Which forgetful blue fish helps search for Nemo?", "Dory", "Disney & Pixar"],
  ["What is the name of the meerkat who befriends young Simba?", "Timon", "Disney & Pixar"],
  ["What is the name of the warthog who befriends young Simba?", "Pumbaa", "Disney & Pixar"],
  ["Who is the wish-granting character that lives in Aladdin's lamp?", "Genie", "Disney & Pixar"],
  ["What is the name of WALL-E's robotic love interest?", "EVE", "Disney & Pixar"],
  ["In what year was the first Toy Story film released?", "1995", "Disney & Pixar"],
  ["Which Pixar film is set inside the mind of a girl named Riley?", "Inside Out", "Disney & Pixar"],
  ["What is the grumpy old balloon-house owner's name in Up?", "Carl Fredricksen", "Disney & Pixar", ["Carl"]],
  ["What is the surname of the superhero family in The Incredibles?", "Parr", "Disney & Pixar"],
  ["What is Mr. Incredible's real name?", "Bob Parr", "Disney & Pixar"],
  ["Who is Sulley's small, one-eyed best friend in Monsters, Inc.?", "Mike Wazowski", "Disney & Pixar", ["Mike"]],
  ["Who is Elsa's younger sister in Frozen?", "Anna", "Disney & Pixar"],
  ["Which Disney princess has magical glowing hair?", "Rapunzel", "Disney & Pixar"],

  ["Who is Frodo's loyal gardener and companion?", "Samwise Gamgee", "The Lord of the Rings", ["Samwise", "Sam Gamgee", "Sam"]],
  ["What creature does Bilbo win the Ring from in The Hobbit?", "Gollum", "The Lord of the Rings"],
  ["Who is the Dark Lord that forged the One Ring?", "Sauron", "The Lord of the Rings"],
  ["What mountain must the Ring be destroyed in?", "Mount Doom", "The Lord of the Rings"],
  ["What is Aragorn's title once crowned king?", "King Elessar", "The Lord of the Rings", ["Elessar"]],
  ["Which dwarf is a member of the Fellowship of the Ring?", "Gimli", "The Lord of the Rings"],
  ["Which wizard betrays the White Council to side with Sauron?", "Saruman", "The Lord of the Rings"],
  ["What giant spider guards the pass into Mordor?", "Shelob", "The Lord of the Rings"],
  ["Who is the elf queen of Lothlórien?", "Galadriel", "The Lord of the Rings"],
  ["What is the name of Aragorn's elvish love interest?", "Arwen", "The Lord of the Rings"],
  ["What is the name of Gandalf's white horse?", "Shadowfax", "The Lord of the Rings"],
  ["Who is the steward of Gondor before Aragorn's return?", "Denethor", "The Lord of the Rings"],
  ["What is the name of the volcanic realm ruled by Sauron?", "Mordor", "The Lord of the Rings"],
  ["What is the name of Frodo's hobbit cousin, also called Pippin?", "Peregrin Took", "The Lord of the Rings", ["Pippin"]],
  ["What is the name of the other hobbit companion, also called Merry?", "Meriadoc Brandybuck", "The Lord of the Rings", ["Merry"]],
  ["What author wrote The Lord of the Rings novels?", "J.R.R. Tolkien", "The Lord of the Rings", ["Tolkien", "JRR Tolkien"]],
  ["In what year did the first Peter Jackson Lord of the Rings film release?", "2001", "The Lord of the Rings"],
  ["What race of tree-like beings inhabits Fangorn Forest?", "Ents", "The Lord of the Rings"],
  ["What is the name of the fortress city of Rohan besieged in The Two Towers?", "Helm's Deep", "The Lord of the Rings"],
  ["What fiery demon does the Fellowship encounter in the Mines of Moria?", "Balrog", "The Lord of the Rings"],

  ["Who plays the paleobotanist Ellie Sattler in the original film?", "Laura Dern", "Jurassic Park"],
  ["What is the name of the second, hidden dinosaur breeding island?", "Isla Sorna", "Jurassic Park"],
  ["Which small, frilled dinosaur spits venom at Dennis Nedry?", "Dilophosaurus", "Jurassic Park"],
  ["Which dinosaur is famous for stalking children in a kitchen scene?", "Velociraptor", "Jurassic Park"],
  ["What is the name of the disgruntled programmer who sabotages the park's systems?", "Dennis Nedry", "Jurassic Park", ["Nedry"]],
  ["What is the name of the genetically engineered hybrid dinosaur in Jurassic World (2015)?", "Indominus rex", "Jurassic Park", ["Indominus Rex"]],
  ["Besides Blue, name one of Owen Grady's other trained raptors.", "Charlie", "Jurassic Park", ["Delta", "Echo"]],
  ["Who plays Claire Dearing in the Jurassic World trilogy?", "Bryce Dallas Howard", "Jurassic Park"],
  ["What hybrid dinosaur menaces guests in Jurassic World: Fallen Kingdom?", "Indoraptor", "Jurassic Park"],
  ["In what year was the original Jurassic Park released?", "1993", "Jurassic Park"],
  ["Who directed the original 1993 Jurassic Park?", "Steven Spielberg", "Jurassic Park"],
  ["Which author wrote the novel Jurassic Park?", "Michael Crichton", "Jurassic Park"],
  ["What flying reptile escapes its enclosure in Jurassic World (2015)?", "Pteranodon", "Jurassic Park"],
  ["What is the name of Tim's older sister in the original Jurassic Park?", "Lex Murphy", "Jurassic Park", ["Lex"]],
  ["What giant aquatic predator is featured in Jurassic World's lagoon show?", "Mosasaurus", "Jurassic Park"],
  ["What substance preserves the ancient DNA used to recreate the dinosaurs?", "Amber", "Jurassic Park"],
  ["What is the name of the animated mascot in the park's explainer film?", "Mr. DNA", "Jurassic Park", ["Mr DNA"]],
  ["What job title does Claire Dearing hold at Jurassic World?", "Operations manager", "Jurassic Park"],
  ["Which Jurassic World film shows dinosaurs living freely among humans worldwide?", "Jurassic World Dominion", "Jurassic Park", ["Dominion"]],
  ["What is Alan Grant's profession?", "Paleontologist", "Jurassic Park"],

  ["Who directed My Neighbor Totoro?", "Hayao Miyazaki", "Studio Ghibli", ["Miyazaki"]],
  ["How many Totoro creatures do Satsuki and Mei encounter?", "Three", "Studio Ghibli"],
  ["What flying creature serves as a bus in My Neighbor Totoro?", "Catbus", "Studio Ghibli", ["Cat Bus"]],
  ["What work name is Chihiro given at the bathhouse in Spirited Away?", "Sen", "Studio Ghibli"],
  ["Who is the antagonist bathhouse owner and witch in Spirited Away?", "Yubaba", "Studio Ghibli"],
  ["What type of being is No-Face in Spirited Away?", "Spirit", "Studio Ghibli"],
  ["In what year was Studio Ghibli founded?", "1985", "Studio Ghibli"],
  ["Who co-founded Studio Ghibli and directed Grave of the Fireflies?", "Isao Takahata", "Studio Ghibli", ["Takahata"]],
  ["Which Ghibli film centers on two siblings during WWII and a firefly-lit tragedy?", "Grave of the Fireflies", "Studio Ghibli"],
  ["What does Sophie turn into under her curse in Howl's Moving Castle?", "An old woman", "Studio Ghibli", ["Old Woman"]],
  ["What is the name of the scarecrow companion in Howl's Moving Castle?", "Turnip Head", "Studio Ghibli"],
  ["What is Ponyo's birth name, given by her father Fujimoto?", "Brunhilde", "Studio Ghibli"],
  ["What is the name of the boy who befriends Ponyo?", "Sōsuke", "Studio Ghibli", ["Sosuke"]],
  ["What is the name of the wolf goddess who raised San in Princess Mononoke?", "Moro", "Studio Ghibli"],
  ["What is San's nickname, referring to her upbringing among wolves?", "Princess Mononoke", "Studio Ghibli"],
  ["What Ghibli film is set on a floating island and involves a boy named Pazu?", "Castle in the Sky", "Studio Ghibli"],
  ["What is the name of Pazu's companion girl with a magical crystal necklace in Castle in the Sky?", "Sheeta", "Studio Ghibli"],
  ["Which 2013 Ghibli film tells the story of aircraft designer Jiro Horikoshi?", "The Wind Rises", "Studio Ghibli"],
  ["What object does Kiki use to fly in Kiki's Delivery Service?", "Broomstick", "Studio Ghibli", ["Broom"]],
  ["What profession does Kiki train to master in Kiki's Delivery Service?", "Witch", "Studio Ghibli"],
]);

add("Books", [
  ["Who is Harry Potter's best friend with red hair?", "Ron Weasley", "Harry Potter", ["Ron"]],
  ["What is the name of Harry's godfather?", "Sirius Black", "Harry Potter", ["Sirius"]],
  ["Who teaches Potions at Hogwarts for most of the series?", "Severus Snape", "Harry Potter", ["Snape"]],
  ["What magical cloak is a family heirloom passed down to Harry?", "Invisibility Cloak", "Harry Potter"],
  ["Which house values loyalty and hard work above all?", "Hufflepuff", "Harry Potter"],
  ["Which house values intelligence and wit?", "Ravenclaw", "Harry Potter"],
  ["What is the name of Hogwarts' half-giant groundskeeper?", "Rubeus Hagrid", "Harry Potter", ["Hagrid"]],
  ["What magical newspaper do wizards read?", "The Daily Prophet", "Harry Potter", ["Daily Prophet"]],
  ["What is the name of the Weasleys' family home?", "The Burrow", "Harry Potter", ["Burrow"]],
  ["What position does Harry play in Quidditch?", "Seeker", "Harry Potter"],
  ["What is the small winged ball that Seekers chase in Quidditch called?", "Golden Snitch", "Harry Potter", ["Snitch"]],
  ["Who is revealed to be the Half-Blood Prince?", "Severus Snape", "Harry Potter", ["Snape"]],
  ["What is Voldemort's snake companion named?", "Nagini", "Harry Potter"],
  ["What magical core do Harry's wand and Voldemort's wand share?", "Phoenix feather", "Harry Potter"],
  ["What is the name of the wizard prison for dark witches and wizards?", "Azkaban", "Harry Potter"],
  ["Who wrote the Harry Potter book series?", "J.K. Rowling", "Harry Potter", ["JK Rowling", "Rowling"]],
  ["In what year was the first Harry Potter book published?", "1997", "Harry Potter"],
  ["What is the name of Harry's Muggle cousin he grows up with?", "Dudley Dursley", "Harry Potter", ["Dudley"]],
  ["What is the name of Hermione's pet cat?", "Crookshanks", "Harry Potter"],
  ["What is the name of the Weasley twins' joke shop in Diagon Alley?", "Weasley's Wizard Wheezes", "Harry Potter"],
]);

add("TV Shows", [
  ["What is the name of Ross's son with Carol?", "Ben", "Friends"],
  ["Who is Ross's first ex-wife who leaves him for a woman?", "Carol Willick", "Friends", ["Carol"]],
  ["What high-fashion brand does Rachel work for later in the series?", "Ralph Lauren", "Friends"],
  ["What is Joey's famous audition catchphrase?", "How You Doin", "Friends", ["How You Doing"]],
  ["Who does Chandler eventually marry?", "Monica Geller", "Friends", ["Monica"]],
  ["Who does Phoebe marry, a scientist played by Paul Rudd?", "Mike Hannigan", "Friends", ["Mike"]],
  ["What is Ross and Monica's parents' surname?", "Geller", "Friends"],
  ["How many times has Ross been divorced by the end of the series?", "Three", "Friends"],
  ["Who plays Rachel Green?", "Jennifer Aniston", "Friends"],
  ["Who plays Ross Geller?", "David Schwimmer", "Friends"],
  ["In what city is Friends set?", "New York City", "Friends", ["New York", "NYC"]],
  ["On what holiday do Chandler's parents announce their divorce, a source of his lifelong dread?", "Thanksgiving", "Friends"],
  ["What is Phoebe Buffay's profession?", "Masseuse", "Friends"],
  ["What color is the door of Monica's apartment?", "Purple", "Friends"],
  ["What is the title of the spin-off show following Joey to Los Angeles?", "Joey", "Friends"],
  ["In what year did Friends premiere?", "1994", "Friends"],
  ["Who co-created Friends alongside Marta Kauffman?", "David Crane", "Friends"],
  ["What is the name of Ross's second wife, whom he marries in England?", "Emily Waltham", "Friends", ["Emily"]],
  ["What was Rachel's job when the series begins, right after fleeing her wedding?", "Waitress", "Friends"],
  ["What is the name of the coffeehouse's regular barista, known for never being seen serving coffee?", "Gunther", "Friends"],

  ["What nickname is given to Mark Sloan?", "McSteamy", "Grey's Anatomy"],
  ["What is the name of Meredith's half-sister who dies in a plane crash?", "Lexie Grey", "Grey's Anatomy", ["Lexie"]],
  ["Which intern deliberately raises a patient's heart rate to move him up the transplant list, causing his death?", "Izzie Stevens", "Grey's Anatomy", ["Izzie"]],
  ["What nickname do the interns give George O'Malley?", "007", "Grey's Anatomy"],
  ["Who does Meredith Grey ultimately marry?", "Derek Shepherd", "Grey's Anatomy", ["Derek"]],
  ["How does Derek Shepherd die?", "Car accident", "Grey's Anatomy"],
  ["What is the hospital renamed to later in the series?", "Grey Sloan Memorial Hospital", "Grey's Anatomy", ["Grey Sloan Memorial"]],
  ["What is Arizona Robbins' surgical specialty?", "Pediatric surgery", "Grey's Anatomy"],
  ["Who is Arizona Robbins' wife, an orthopedic surgeon?", "Callie Torres", "Grey's Anatomy", ["Callie"]],
  ["What is the name of the gunman who attacks the hospital in the season 6 finale?", "Gary Clark", "Grey's Anatomy"],
  ["What is Jackson Avery's surgical specialty?", "Plastic surgery", "Grey's Anatomy"],
  ["What branch of the military did Owen Hunt serve in?", "Army", "Grey's Anatomy"],
  ["What is Owen Hunt's surgical specialty?", "Trauma surgery", "Grey's Anatomy"],
  ["Who plays Meredith Grey?", "Ellen Pompeo", "Grey's Anatomy"],
  ["In what U.S. city is Grey's Anatomy set?", "Seattle", "Grey's Anatomy"],
  ["What is the name of Meredith and Derek's first daughter?", "Zola", "Grey's Anatomy"],
  ["What Grey's Anatomy spin-off follows Seattle firefighters?", "Station 19", "Grey's Anatomy"],
  ["In what year did Grey's Anatomy premiere?", "2005", "Grey's Anatomy"],
  ["Who is Cristina Yang's cardiothoracic mentor and on-off fiancé?", "Preston Burke", "Grey's Anatomy", ["Burke"]],
  ["What is the name of Miranda Bailey's son, nicknamed after his father?", "Tuck", "Grey's Anatomy"],

  ["What is Sheldon's father's job?", "Football coach", "Young Sheldon"],
  ["Who provides adult Sheldon's narration voice-over?", "Jim Parsons", "Young Sheldon"],
  ["Who is Sheldon's best friend at school?", "Tam Nguyen", "Young Sheldon", ["Tam"]],
  ["What is the name of the parent series featuring adult Sheldon?", "The Big Bang Theory", "Young Sheldon"],
  ["What is Georgie's full name?", "George Cooper Jr.", "Young Sheldon", ["George Cooper Junior"]],
  ["What religious denomination does Mary Cooper practice?", "Baptist", "Young Sheldon"],
  ["Which university does adult Sheldon work at as a physicist?", "Caltech", "Young Sheldon"],
  ["What is Meemaw's real first name?", "Connie", "Young Sheldon", ["Constance"]],
  ["What card game does Meemaw teach Sheldon?", "Poker", "Young Sheldon"],
  ["In which U.S. state is Young Sheldon set?", "Texas", "Young Sheldon"],
  ["Which actor plays George Cooper Sr.?", "Lance Barber", "Young Sheldon"],
  ["Which actress plays Mary Cooper?", "Zoe Perry", "Young Sheldon"],
  ["What is the name of Sheldon's high school?", "Medford High School", "Young Sheldon", ["Medford High"]],
  ["On which network did Young Sheldon originally air?", "CBS", "Young Sheldon"],
  ["In what year did Young Sheldon premiere?", "2017", "Young Sheldon"],
  ["What is the name of the direct sequel series about Georgie and Mandy?", "Georgie & Mandy's First Marriage", "Young Sheldon", ["Georgie and Mandy's First Marriage"]],
  ["Who is Georgie's older girlfriend who becomes a major character?", "Mandy McAllister", "Young Sheldon", ["Mandy"]],
  ["What sport does Sheldon's father coach at the high school?", "Football", "Young Sheldon"],
  ["What is the name of Sheldon's mentor and professor at East Texas Tech?", "John Sturgis", "Young Sheldon", ["Dr. Sturgis", "Sturgis"]],
  ["Which actor plays Dr. John Sturgis?", "Wallace Shawn", "Young Sheldon"],

  ["What is Sheldon Cooper's middle name?", "Lee", "The Big Bang Theory"],
  ["Who does Sheldon eventually marry?", "Amy Farrah Fowler", "The Big Bang Theory", ["Amy"]],
  ["What is the name of Howard's wife, a microbiologist?", "Bernadette Rostenkowski", "The Big Bang Theory", ["Bernadette"]],
  ["What is Bernadette's scientific profession?", "Microbiologist", "The Big Bang Theory"],
  ["Which Texas university did Sheldon attend before Caltech?", "East Texas Tech", "The Big Bang Theory"],
  ["What is the name of Raj's dog?", "Cinnamon", "The Big Bang Theory"],
  ["What condition initially prevents Raj from speaking to women?", "Selective mutism", "The Big Bang Theory"],
  ["Who does Leonard Hofstadter marry?", "Penny", "The Big Bang Theory"],
  ["What was Penny's job when the series begins?", "Waitress", "The Big Bang Theory"],
  ["What restaurant chain does Penny waitress at?", "The Cheesecake Factory", "The Big Bang Theory", ["Cheesecake Factory"]],
  ["What prestigious prize do Sheldon and Amy win in the series finale?", "Nobel Prize", "The Big Bang Theory"],
  ["In what field do Sheldon and Amy win their Nobel Prize?", "Physics", "The Big Bang Theory"],
  ["What is the first name of Howard's mother, often heard offscreen?", "Debbie", "The Big Bang Theory"],
  ["What U.S. space agency does Howard travel to space with?", "NASA", "The Big Bang Theory"],
  ["In what year did The Big Bang Theory premiere?", "2007", "The Big Bang Theory"],
  ["Who co-created The Big Bang Theory with Bill Prady?", "Chuck Lorre", "The Big Bang Theory"],
  ["What game do the friends play that adds two options to rock-paper-scissors?", "Rock-Paper-Scissors-Lizard-Spock", "The Big Bang Theory", ["Rock Paper Scissors Lizard Spock"]],
  ["What is Leonard Hofstadter's scientific profession?", "Experimental physicist", "The Big Bang Theory"],
  ["What is the name of Leonard's overbearing psychiatrist mother?", "Beverly Hofstadter", "The Big Bang Theory", ["Beverly"]],
  ["In which California city is The Big Bang Theory set?", "Pasadena", "The Big Bang Theory"],

  ["What is Barney Stinson's rallying catchphrase before a big night out?", "Suit Up", "How I Met Your Mother"],
  ["What does Marshall dream of doing professionally to help the planet?", "Environmental lawyer", "How I Met Your Mother"],
  ["What is Ted Mosby's profession?", "Architect", "How I Met Your Mother"],
  ["What bank does Barney work for throughout most of the series?", "Goliath National Bank", "How I Met Your Mother", ["GNB"]],
  ["What news network does Robin work for as a journalist?", "World Wide News", "How I Met Your Mother", ["WWN"]],
  ["Who does Robin ultimately marry at the end of the series?", "Barney Stinson", "How I Met Your Mother", ["Barney"]],
  ["What career does Lily briefly pursue in San Francisco, giving up teaching?", "Artist", "How I Met Your Mother"],
  ["What is the nickname for the multi-season wager where Marshall can slap Barney?", "The Slap Bet", "How I Met Your Mother", ["Slap Bet"]],
  ["How many total slaps make up the complete Slap Bet saga?", "Eight", "How I Met Your Mother"],
  ["What is the name of Ted's girlfriend who leaves him at the altar?", "Stella Zinman", "How I Met Your Mother", ["Stella"]],
  ["Besides The Playbook, what other rulebook does Barney reference?", "The Bro Code", "How I Met Your Mother", ["Bro Code"]],
  ["What is the name of Lily and Marshall's son?", "Marvin", "How I Met Your Mother"],
  ["What college did Ted, Marshall, and Lily attend together?", "Wesleyan University", "How I Met Your Mother", ["Wesleyan"]],
  ["In which U.S. city is How I Met Your Mother primarily set?", "New York City", "How I Met Your Mother", ["New York", "NYC"]],
  ["In what year did How I Met Your Mother premiere?", "2005", "How I Met Your Mother"],
  ["What instrument does Tracy, the Mother, play in a band?", "Bass guitar", "How I Met Your Mother", ["Bass"]],
  ["What job title does Barney's business card famously list?", "Please", "How I Met Your Mother"],
  ["What is the name of MacLaren's regular bartender?", "Carl", "How I Met Your Mother"],
  ["Who is Ted's boss at his first architecture firm, played by Bryan Cranston?", "Hammond Druthers", "How I Met Your Mother", ["Druthers"]],
  ["What is the profession of Ted's early girlfriend Victoria?", "Pastry chef", "How I Met Your Mother"],
]);

export const QUESTIONS = bank;
export const THEMES = [...new Set(bank.map((q) => q.theme).filter(Boolean))];
