// Compact curated launch bank. Each category has 20 questions so any single
// category can support the maximum game length without repeats.
const bank = [];
const slug = (s) => s.toLowerCase().normalize("NFKD").replace(/[\u0300-\u036f]/g, "").replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
function add(category, rows) {
  const existing = bank.filter((q) => q.category === category).length;
  rows.forEach(([prompt, answer, theme = null, aliases = []], index) => bank.push({
    id: `${slug(category)}-${String(existing + index + 1).padStart(3, "0")}`,
    category, theme, prompt, answer,
    acceptedAnswers: [answer, ...aliases].map((text) => ({ text, display: text !== answer })),
    match: { mode: /^\d{4}$/.test(answer) ? "year" : "text", fuzzy: !/^\d{4}$/.test(answer), optionalArticles: true },
    explanation: `${answer} is the accepted answer.`,
  }));
}

add("Movies", [
  ["What is the name of Han Solo's ship?", "Millennium Falcon", "Star Wars", ["the Millennium Falcon"]],
  ["Who is Luke Skywalker's twin sister?", "Leia Organa", "Star Wars", ["Princess Leia", "Leia"]],
  ["What species is Chewbacca?", "Wookiee", "Star Wars", ["Wookie"]],
  ["What is Baby Yoda's actual name?", "Grogu", "Star Wars"],
  ["Which Sith Lord was once Anakin Skywalker?", "Darth Vader", "Star Wars", ["Vader"]],
  ["What metal is bonded to Wolverine's skeleton?", "Adamantium", "Marvel Cinematic Universe"],
  ["What is Thor's hammer called?", "Mjolnir", "Marvel Cinematic Universe", ["Mjölnir"]],
  ["What nation is Black Panther king of?", "Wakanda", "Marvel Cinematic Universe"],
  ["What is Captain America's shield primarily made from?", "Vibranium", "Marvel Cinematic Universe"],
  ["What is Tony Stark's superhero name?", "Iron Man", "Marvel Cinematic Universe"],
  ["What kind of fish is Nemo?", "Clownfish", "Disney & Pixar", ["clown fish"]],
  ["Who is the space ranger in Toy Story?", "Buzz Lightyear", "Disney & Pixar", ["Buzz"]],
  ["What is the name of the rat chef in Ratatouille?", "Remy", "Disney & Pixar"],
  ["Which princess has a tiger named Rajah?", "Jasmine", "Disney & Pixar", ["Princess Jasmine"]],
  ["What is the snowman's name in Frozen?", "Olaf", "Disney & Pixar"],
  ["Who carries the One Ring to Mordor?", "Frodo Baggins", "The Lord of the Rings", ["Frodo"]],
  ["What creature does Gollum call his precious?", "The One Ring", "The Lord of the Rings", ["One Ring", "ring"]],
  ["Who is the wizard leader of the Fellowship?", "Gandalf", "The Lord of the Rings"],
  ["What dinosaur is the main threat in the first Jurassic Park?", "Tyrannosaurus rex", "Jurassic Park", ["T. rex", "T-Rex"]],
  ["Who directed Spirited Away?", "Hayao Miyazaki", "Studio Ghibli", ["Miyazaki"]],
]);

// Every named Movie theme has at least six entries, enough for the shortest
// focused game. General mixed games still balance at the top-level category.
add("Movies", [
  ["Who built the protocol droid C-3PO?", "Anakin Skywalker", "Star Wars", ["Anakin"]],
  ["Which Infinity Stone was set in Vision's forehead?", "Mind Stone", "Marvel Cinematic Universe", ["the Mind Stone"]],
  ["Who is Simba's father in The Lion King?", "Mufasa", "Disney & Pixar"],
  ["What is the reforged name of Aragorn's sword?", "Andúril", "The Lord of the Rings", ["Anduril"]],
  ["Which elf serves as the Fellowship's archer?", "Legolas", "The Lord of the Rings"],
  ["Which land is ruled by the horse-lords?", "Rohan", "The Lord of the Rings"],
  ["On what fictional island is the original Jurassic Park built?", "Isla Nublar", "Jurassic Park", ["Nublar"]],
  ["Who founded Jurassic Park in the first film?", "John Hammond", "Jurassic Park", ["Hammond"]],
  ["Which paleontologist is played by Sam Neill?", "Alan Grant", "Jurassic Park", ["Dr. Alan Grant", "Grant"]],
  ["What insect preserved in amber provides dinosaur DNA?", "Mosquito", "Jurassic Park", ["a mosquito"]],
  ["What genetics company created Jurassic Park's dinosaurs?", "InGen", "Jurassic Park", ["International Genetic Technologies"]],
  ["What forest spirit befriends Satsuki and Mei?", "Totoro", "Studio Ghibli", ["My Neighbor Totoro"]],
  ["What is the name of Kiki's black cat?", "Jiji", "Studio Ghibli"],
  ["Who owns the moving castle in Howl's Moving Castle?", "Howl", "Studio Ghibli", ["Howl Pendragon"]],
  ["Who is the young Emishi prince in Princess Mononoke?", "Ashitaka", "Studio Ghibli"],
  ["What kind of creature is Ponyo at the beginning of her film?", "Goldfish", "Studio Ghibli", ["fish"]],
]);

add("Movies", [
  ["On which planet does Yoda live in exile?", "Dagobah", "Star Wars"],
  ["What command triggered the clone army to turn on the Jedi?", "Order 66", "Star Wars", ["Execute Order 66"]],
  ["On which desert planet does Rey live when first introduced?", "Jakku", "Star Wars"],
  ["Which bounty hunter wears armor inherited from Jango Fett?", "Boba Fett", "Star Wars", ["Boba"]],
  ["What is the Hulk's human name?", "Bruce Banner", "Marvel Cinematic Universe", ["Dr. Bruce Banner", "Banner"]],
  ["What is Natasha Romanoff's superhero name?", "Black Widow", "Marvel Cinematic Universe"],
  ["Which Infinity Stone was housed in the Tesseract?", "Space Stone", "Marvel Cinematic Universe", ["the Space Stone"]],
  ["What superhero title is held by Wakanda's protector?", "Black Panther", "Marvel Cinematic Universe"],
  ["What is the family surname in Encanto?", "Madrigal", "Disney & Pixar", ["the Madrigals", "Madrigal family"]],
  ["What city do the monsters inhabit in Monsters, Inc.?", "Monstropolis", "Disney & Pixar"],
  ["What is the name of the Wilderness Explorer in Up?", "Russell", "Disney & Pixar"],
  ["What are Cinderella's two best-known mouse friends?", "Jaq and Gus", "Disney & Pixar", ["Jaq & Gus", "Gus and Jaq"]],
  ["What peaceful homeland do Frodo and Bilbo come from?", "The Shire", "The Lord of the Rings", ["Shire"]],
  ["Which kingdom does Boromir defend?", "Gondor", "The Lord of the Rings"],
  ["What was Gollum's name before he took the Ring?", "Sméagol", "The Lord of the Rings", ["Smeagol"]],
  ["Which Ent leads the march on Isengard?", "Treebeard", "The Lord of the Rings"],
  ["Which chaos theorist is played by Jeff Goldblum?", "Ian Malcolm", "Jurassic Park", ["Dr. Ian Malcolm", "Malcolm"]],
  ["What is the name of Owen Grady's trained velociraptor?", "Blue", "Jurassic Park"],
  ["Who trains velociraptors in Jurassic World?", "Owen Grady", "Jurassic Park", ["Owen"]],
  ["Which towering dinosaur is the first living dinosaur the visitors see in Jurassic Park?", "Brachiosaurus", "Jurassic Park"],
  ["What is the heroine's name in Spirited Away?", "Chihiro", "Studio Ghibli", ["Chihiro Ogino", "Sen"]],
  ["What fire demon powers Howl's moving castle?", "Calcifer", "Studio Ghibli"],
  ["Which princess explores the toxic jungle in Nausicaä of the Valley of the Wind?", "Nausicaä", "Studio Ghibli", ["Nausicaa"]],
  ["What is the floating castle called in Castle in the Sky?", "Laputa", "Studio Ghibli"],
]);

add("Movies", [
  ["Who directed Titanic?", "James Cameron", null, ["Cameron"]],
  ["What name does Thomas Anderson use in The Matrix?", "Neo"],
  ["What is the crime-family surname in The Godfather?", "Corleone", null, ["the Corleone family"]],
  ["What planet is E.T. trying to return to?", "His home planet", null, ["home"]],
  ["What kind of animal terrorizes Amity Island in Jaws?", "Great white shark", null, ["shark"]],
  ["What car is used as the time machine in Back to the Future?", "DeLorean", null, ["DMC DeLorean"]],
  ["Who follows the Yellow Brick Road in The Wizard of Oz?", "Dorothy Gale", null, ["Dorothy"]],
  ["What is the first name of Russell Crowe's character in Gladiator?", "Maximus", null, ["Maximus Decimus Meridius"]],
  ["On what moon is Avatar primarily set?", "Pandora"],
  ["What object is Cobb's totem in Inception?", "Spinning top", null, ["top"]],
  ["In which Moroccan city is the film Casablanca set?", "Casablanca"],
  ["What prison gives The Shawshank Redemption its title?", "Shawshank State Penitentiary", null, ["Shawshank Prison", "Shawshank"]],
  ["In which city do the Ghostbusters operate?", "New York City", null, ["New York", "NYC"]],
  ["What is Indiana Jones's profession?", "Archaeologist", null, ["an archaeologist"]],
  ["Who is the central IMF agent in the Mission: Impossible films?", "Ethan Hunt", null, ["Hunt"]],
]);

add("Books", [
  ["What house is Harry Potter sorted into?", "Gryffindor", "Harry Potter"],
  ["What is Harry Potter's owl named?", "Hedwig", "Harry Potter"],
  ["Who is Hogwarts' headmaster at the start of the series?", "Albus Dumbledore", "Harry Potter", ["Dumbledore"]],
  ["What platform does the Hogwarts Express depart from?", "Platform 9¾", "Harry Potter", ["Platform 9 3/4", "9¾", "9 3/4"]],
  ["What sport is played on flying broomsticks?", "Quidditch", "Harry Potter"],
  ["What is Hermione's surname?", "Granger", "Harry Potter", ["Hermione Granger"]],
  ["What creature guards the Philosopher's Stone trapdoor?", "Fluffy", "Harry Potter", ["three-headed dog"]],
  ["What spell disarms an opponent?", "Expelliarmus", "Harry Potter"],
  ["Which house has a snake as its emblem?", "Slytherin", "Harry Potter"],
  ["What is Voldemort's birth name?", "Tom Riddle", "Harry Potter", ["Tom Marvolo Riddle"]],
  ["Who wrote Pride and Prejudice?", "Jane Austen"],
  ["Who wrote 1984?", "George Orwell"],
  ["What is Sherlock Holmes's street address?", "221B Baker Street", null, ["221B Baker St"]],
  ["Which novel begins with the character Scout Finch?", "To Kill a Mockingbird"],
  ["Who wrote The Little Prince?", "Antoine de Saint-Exupéry", null, ["Antoine de Saint Exupery", "Saint-Exupéry"]],
  ["What is the surname of the sisters in Little Women?", "March"],
  ["Who created the detective Hercule Poirot?", "Agatha Christie"],
  ["What is the first book of The Chronicles of Narnia by publication order?", "The Lion, the Witch and the Wardrobe", null, ["Lion Witch and Wardrobe"]],
  ["Who wrote The Hobbit?", "J. R. R. Tolkien", null, ["JRR Tolkien", "Tolkien"]],
  ["What whale is pursued in Moby-Dick?", "Moby Dick", null, ["the white whale"]],
]);

add("The '90s", [
  ["In what year did the World Wide Web become publicly available?", "1991"],
  ["In what year was the first SMS text message sent?", "1992"],
  ["In what year did Jurassic Park premiere?", "1993"],
  ["In what year did Friends first air?", "1994"],
  ["In what year was Windows 95 released?", "1995"],
  ["In what year did Pokémon debut in Japan?", "1996"],
  ["In what year did the first Harry Potter novel publish in the UK?", "1997"],
  ["In what year was Google founded?", "1998"],
  ["In what year did The Matrix premiere?", "1999"],
  ["Which virtual pet toy became a global craze in the late 1990s?", "Tamagotchi"],
  ["Which girl group released Wannabe?", "Spice Girls", null, ["the Spice Girls"]],
  ["Which handheld Nintendo console was a defining 1990s toy?", "Game Boy", null, ["Nintendo Game Boy"]],
  ["What dance craze accompanied Los del Río's hit song?", "Macarena", null, ["the Macarena"]],
  ["Which sitcom featured Will Smith moving to Bel-Air?", "The Fresh Prince of Bel-Air", null, ["Fresh Prince of Bel Air"]],
  ["What storage format commonly held 1.44 MB on personal computers?", "Floppy disk", null, ["3.5-inch floppy disk", "floppy"]],
  ["Which arcade fighting series introduced Scorpion and Sub-Zero?", "Mortal Kombat"],
  ["Which singer was known as the Princess of Pop after ...Baby One More Time?", "Britney Spears", null, ["Britney"]],
  ["What was the name of the cloned sheep announced in 1997?", "Dolly", null, ["Dolly the sheep"]],
  ["Which basketball star led the Chicago Bulls to six 1990s championships?", "Michael Jordan", null, ["Jordan"]],
  ["Which internet service was famous for the phrase You've got mail?", "AOL", null, ["America Online"]],
]);

add("Food & Drink", [
  ["What legume is the main ingredient in hummus?", "Chickpeas", null, ["chickpea", "garbanzo beans"]],
  ["What fruit is dried to make a prune?", "Plum", null, ["plums"]],
  ["Which cheese is traditionally used on pizza Margherita?", "Mozzarella"],
  ["What grain is used to make risotto?", "Rice", null, ["arborio rice"]],
  ["What is the Japanese name for green tea powder?", "Matcha"],
  ["Which herb is the base of traditional pesto Genovese?", "Basil"],
  ["What pastry is used for a classic profiterole?", "Choux pastry", null, ["choux"]],
  ["What Mexican dish folds a tortilla around a filling?", "Taco", null, ["tacos"]],
  ["Which spice gives many curries a yellow color?", "Turmeric"],
  ["What is tofu primarily made from?", "Soybeans", null, ["soy beans", "soya beans"]],
  ["What citrus fruit flavors Earl Grey tea?", "Bergamot"],
  ["Which country is the origin of paella?", "Spain"],
  ["What noodle dish is associated with Bologna?", "Tagliatelle al ragù", null, ["tagliatelle ragu", "tagliatelle"]],
  ["What nut is used in marzipan?", "Almond", null, ["almonds"]],
  ["Which sauce is made from egg yolk and oil as an emulsion?", "Mayonnaise", null, ["mayo"]],
  ["What is the primary spirit in a mojito?", "Rum", null, ["white rum"]],
  ["What dairy product is churned to make butter?", "Cream"],
  ["Which fruit has varieties called Hass and Fuerte?", "Avocado"],
  ["What is the Italian word for ice cream?", "Gelato"],
  ["Which bean is used to make chocolate?", "Cocoa bean", null, ["cacao", "cacao bean", "cacao beans", "cocoa", "cocoa beans"]],
]);

add("Animals", [
  ["What is the largest living animal?", "Blue whale"],
  ["What is a group of lions called?", "Pride", null, ["a pride"]],
  ["Which mammal lays eggs and has a duck-like bill?", "Platypus"],
  ["What is the fastest land animal?", "Cheetah"],
  ["Which bird is the largest living bird?", "Ostrich"],
  ["What do giant pandas mainly eat?", "Bamboo"],
  ["Which animal is known for changing color using chromatophores?", "Chameleon"],
  ["What is a baby goat called?", "Kid", null, ["a kid"]],
  ["Which marine mammal uses tusks and lives in the Arctic?", "Walrus"],
  ["How many legs does an arachnid have?", "Eight", null, ["8"]],
  ["Which animal has black skin beneath white fur?", "Polar bear"],
  ["What is the only mammal capable of sustained true flight?", "Bat", null, ["bats"]],
  ["Which insect makes honey?", "Honey bee", null, ["bee", "bees"]],
  ["What is a male deer commonly called?", "Stag", null, ["buck"]],
  ["Which amphibian begins life as a tadpole?", "Frog", null, ["frogs"]],
  ["What is the largest species of shark?", "Whale shark"],
  ["Which animal is famous for a pouch and powerful hind legs?", "Kangaroo"],
  ["What is a group of wolves called?", "Pack", null, ["a pack"]],
  ["Which flightless bird is native to New Zealand?", "Kiwi", null, ["kiwi bird"]],
  ["What do you call an animal active mainly at night?", "Nocturnal", null, ["nocturnal animal"]],
]);

add("Science", [
  ["What planet is known as the Red Planet?", "Mars"],
  ["What gas do plants absorb during photosynthesis?", "Carbon dioxide", null, ["CO2"]],
  ["What is the chemical symbol for gold?", "Au"],
  ["What force keeps planets in orbit?", "Gravity", null, ["gravitation"]],
  ["What is the center of an atom called?", "Nucleus", null, ["the nucleus"]],
  ["Which organ pumps blood around the human body?", "Heart", null, ["the heart"]],
  ["What is water's chemical formula?", "H2O", null, ["H₂O"]],
  ["What is the nearest star to Earth?", "The Sun", null, ["Sun"]],
  ["What process turns a liquid into a gas?", "Evaporation", null, ["vaporization"]],
  ["What scale measures mineral hardness?", "Mohs scale", null, ["Mohs"]],
  ["What particle has a negative electric charge?", "Electron", null, ["an electron"]],
  ["What is the largest organ of the human body?", "Skin", null, ["the skin"]],
  ["Which planet has the most prominent ring system?", "Saturn"],
  ["What branch of science studies living things?", "Biology"],
  ["What is the boiling point of water at sea level in Celsius?", "100", null, ["100°C", "100 degrees Celsius"]],
  ["What molecule carries genetic instructions in most organisms?", "DNA", null, ["deoxyribonucleic acid"]],
  ["What device records earthquakes?", "Seismograph", null, ["seismometer"]],
  ["Which blood cells carry oxygen?", "Red blood cells", null, ["erythrocytes"]],
  ["What is the speed of light commonly rounded to in kilometers per second?", "300000", null, ["300,000"]],
  ["What is the pH of a neutral solution at room temperature?", "7", null, ["seven"]],
]);

add("Sports", [
  ["How many players does one soccer team field at kickoff?", "Eleven", null, ["11"]],
  ["In tennis, what word means a score of zero?", "Love"],
  ["How many points is a basketball free throw worth?", "One", null, ["1"]],
  ["What sport uses a shuttlecock?", "Badminton"],
  ["How many rings are on the Olympic symbol?", "Five", null, ["5"]],
  ["What sport is played at Wimbledon?", "Tennis"],
  ["In baseball, how many strikes make an out?", "Three", null, ["3"]],
  ["What color jersey does the Tour de France leader wear?", "Yellow"],
  ["What country originated judo?", "Japan"],
  ["What is three under par on one golf hole called?", "Albatross", null, ["double eagle"]],
  ["How long is an Olympic swimming pool in meters?", "50", null, ["50 meters", "fifty"]],
  ["Which chess piece moves in an L shape?", "Knight", null, ["the knight"]],
  ["What sport features the pommel horse?", "Gymnastics"],
  ["How many points is a rugby union try worth?", "Five", null, ["5"]],
  ["What combat sport uses épée, foil, and sabre?", "Fencing"],
  ["What is the maximum score with one dart?", "60", null, ["sixty"]],
  ["In volleyball, how many players per team are on court?", "Six", null, ["6"]],
  ["What race is 42.195 kilometers long?", "Marathon", null, ["a marathon"]],
  ["What sport uses stones and brooms on ice?", "Curling"],
  ["Which martial art's name means gentle way?", "Judo"],
]);

add("General Knowledge", [
  ["What is the capital of Canada?", "Ottawa"], ["How many continents are commonly recognized?", "Seven", null, ["7"]],
  ["What is the longest river in South America?", "Amazon River", null, ["Amazon"]], ["Which language has the most native speakers?", "Mandarin Chinese", null, ["Mandarin"]],
  ["What is the currency of Japan?", "Yen", null, ["Japanese yen"]], ["Who painted the Mona Lisa?", "Leonardo da Vinci", null, ["da Vinci", "Leonardo"]],
  ["What is the smallest prime number?", "Two", null, ["2"]], ["Which ocean is the largest?", "Pacific Ocean", null, ["Pacific"]],
  ["What is the capital of New Zealand?", "Wellington"], ["Which country is shaped like a boot?", "Italy"],
  ["What is the Roman numeral for fifty?", "L"], ["Who composed The Four Seasons?", "Antonio Vivaldi", null, ["Vivaldi"]],
  ["What is the tallest mountain above sea level?", "Mount Everest", null, ["Everest"]], ["Which desert covers much of northern Africa?", "Sahara", null, ["Sahara Desert"]],
  ["What is the capital of Brazil?", "Brasília", null, ["Brasilia"]], ["Which metal is liquid at room temperature?", "Mercury"],
  ["How many sides does a dodecagon have?", "Twelve", null, ["12"]], ["What is the largest country by land area?", "Russia"],
  ["Which instrument has 88 keys on a standard model?", "Piano"], ["What is the study of maps called?", "Cartography"],
]);

add("Philippine History", [
  ["Who wrote Noli Me Tángere?", "José Rizal", null, ["Jose Rizal", "Rizal"]], ["What secret society did Andrés Bonifacio found?", "Katipunan", null, ["KKK"]],
  ["On what date is Philippine Independence Day celebrated?", "June 12", null, ["12 June"]], ["Who was the first President of the Philippine Republic?", "Emilio Aguinaldo", null, ["Aguinaldo"]],
  ["In what city was the 1898 declaration of independence proclaimed?", "Kawit", null, ["Kawit, Cavite"]], ["Who is known as the Great Plebeian?", "Andrés Bonifacio", null, ["Andres Bonifacio", "Bonifacio"]],
  ["What was the precolonial writing system used by many Tagalog speakers?", "Baybayin"], ["Who painted the Spoliarium?", "Juan Luna", null, ["Luna"]],
  ["What treaty ended the Spanish-American War and ceded the Philippines to the United States?", "Treaty of Paris", null, ["Treaty of Paris of 1898"]], ["Who was called the Sublime Paralytic?", "Apolinario Mabini", null, ["Mabini"]],
  ["What movement campaigned for reforms under Spanish rule?", "Propaganda Movement", null, ["Propaganda"]], ["Who founded La Liga Filipina?", "José Rizal", null, ["Jose Rizal", "Rizal"]],
  ["What newspaper was published by the Propaganda Movement in Spain?", "La Solidaridad"], ["Who was the first woman President of the Philippines?", "Corazon Aquino", null, ["Cory Aquino", "Aquino"]],
  ["What battle in 1521 resulted in the death of Ferdinand Magellan?", "Battle of Mactan", null, ["Mactan"]], ["Who led Filipino forces at the Battle of Mactan?", "Lapulapu", null, ["Lapu-Lapu", "Lapu Lapu"]],
  ["What constitution established the First Philippine Republic?", "Malolos Constitution", null, ["Constitution of Malolos"]], ["Where was José Rizal exiled?", "Dapitan", null, ["Dapitan City"]],
  ["Which three priests are collectively remembered as Gomburza?", "Gómez, Burgos, and Zamora", null, ["Gomez Burgos Zamora", "Mariano Gomez Jose Burgos Jacinto Zamora"]], ["What is the historic walled district of Manila called?", "Intramuros"],
]);

add("Philippine Geography", [
  ["What is the capital of the Philippines?", "Manila"], ["What is the largest Philippine island?", "Luzon"],
  ["What is the highest mountain in the Philippines?", "Mount Apo", null, ["Mt Apo", "Apo"]], ["Which island is famous for the Chocolate Hills?", "Bohol"],
  ["Which province contains the Banaue Rice Terraces?", "Ifugao"], ["What is the longest river in the Philippines?", "Cagayan River", null, ["Rio Grande de Cagayan"]],
  ["Which volcano is famous for its near-perfect cone?", "Mayon Volcano", null, ["Mayon"]], ["What sea lies west of the Philippine archipelago?", "West Philippine Sea", null, ["South China Sea"]],
  ["Which city is known as the Summer Capital of the Philippines?", "Baguio", null, ["Baguio City"]], ["What is the smallest Philippine province by land area?", "Batanes"],
  ["Which island group lies between Luzon and Mindanao?", "Visayas", null, ["the Visayas"]], ["What strait separates Samar and Leyte?", "San Juanico Strait", null, ["San Juanico"]],
  ["Which province is home to El Nido?", "Palawan"], ["Which lake is the largest in the Philippines?", "Laguna de Bay"],
  ["Which city is called the Queen City of the South?", "Cebu City", null, ["Cebu"]], ["What gulf borders Metro Manila?", "Manila Bay"],
  ["Which active volcano sits on an island within a lake in Batangas?", "Taal Volcano", null, ["Taal"]], ["Which province is Siargao part of?", "Surigao del Norte"],
  ["What channel separates Batanes from the Babuyan Islands?", "Balintang Channel", null, ["Balintang"]], ["Which river runs through Cagayan de Oro and is known for whitewater rafting?", "Cagayan de Oro River", null, ["Cagayan River"]],
]);

add("Filipino Culture & Language", [
  ["What Filipino value refers to communal unity and cooperation?", "Bayanihan"], ["What respectful words are commonly added when speaking to elders?", "Po and opo", null, ["po at opo", "po opo"]],
  ["What is the Filipino martial art also called Eskrima?", "Arnis", null, ["Kali"]], ["What woven sleeping mat is common in Filipino homes?", "Banig"],
  ["What giant lantern festival is held in San Fernando, Pampanga?", "Ligligan Parul", null, ["Giant Lantern Festival"]], ["What harvest festival in Lucban decorates houses with kiping?", "Pahiyas Festival", null, ["Pahiyas"]],
  ["What mythical creature is said to separate its upper body and fly at night?", "Manananggal"], ["What Filipino term describes the spirit of shared identity and empathy?", "Pakikipagkapwa", null, ["kapwa"]],
  ["What is the national language of the Philippines?", "Filipino"], ["What word means older sister in Filipino?", "Ate"],
  ["What word means older brother in Filipino?", "Kuya"], ["What bamboo dance involves stepping between moving poles?", "Tinikling"],
  ["What formal Filipino shirt is often made from piña fabric?", "Barong Tagalog", null, ["barong"]], ["What gesture places an elder's hand on one's forehead?", "Pagmamano", null, ["mano po", "mano"]],
  ["What star-shaped Christmas lantern is displayed in Filipino homes?", "Parol"], ["What Filipino serenade tradition is called?", "Harana"],
  ["What epic chant of the Ifugao is recognized by UNESCO?", "Hudhud", null, ["Hudhud chants"]], ["What is the Filipino term for a neighborhood community?", "Barangay"],
  ["What colorful festival in Iloilo honors the Santo Niño?", "Dinagyang Festival", null, ["Dinagyang"]], ["What festival in Aklan is known for soot-darkened faces and Ati costumes?", "Ati-Atihan", null, ["Ati Atihan"]],
]);

add("Filipino Entertainment", [
  ["Who is known as the King of Philippine Movies?", "Fernando Poe Jr.", null, ["FPJ", "Fernando Poe Junior"]], ["Who is known as the Asia's Songbird?", "Regine Velasquez", null, ["Regine Velasquez-Alcasid", "Regine"]],
  ["Which Filipino singer recorded Anak?", "Freddie Aguilar", null, ["Ka Freddie"]], ["What long-running noontime show introduced the segment Juan for All, All for Juan?", "Eat Bulaga", null, ["Eat Bulaga!"]],
  ["Who created the comic-book superhero Darna?", "Mars Ravelo", null, ["Ravelo"]], ["What is the superhero identity of Narda?", "Darna"],
  ["Which Filipino band recorded Eraserheads' hit Ang Huling El Bimbo?", "Eraserheads", null, ["The Eraserheads", "E-Heads"]], ["Who is known as the Megastar of Philippine entertainment?", "Sharon Cuneta", null, ["Sharon"]],
  ["Which singer is known as Mr. Pure Energy?", "Gary Valenciano", null, ["Gary V", "Gary Valenciano"]], ["Who directed the film Himala?", "Ishmael Bernal", null, ["Bernal"]],
  ["Which actress delivered the famous Walang himala line in Himala?", "Nora Aunor", null, ["Nora"]], ["What Filipino singing competition uses four coaches with turning chairs?", "The Voice of the Philippines", null, ["The Voice Philippines"]],
  ["Who composed the patriotic song Bayan Ko?", "Constancio de Guzman", null, ["Constancio de Guzmán", "de Guzman"]], ["Which OPM band recorded With a Smile?", "Eraserheads", null, ["The Eraserheads"]],
  ["Who is known as the Comedy King of the Philippines?", "Dolphy", null, ["Rodolfo Quizon"]], ["Which fantasy TV series features the kingdoms Lireo, Sapiro, Hathoria, and Adamya?", "Encantadia"],
  ["What is the title of Lea Salonga's character in Miss Saigon?", "Kim"], ["Which Filipina singer provided the singing voices of Jasmine and Mulan?", "Lea Salonga", null, ["Lea"]],
  ["What 2015 romantic film paired Enrique Gil and Liza Soberano in Baguio?", "Just the Way You Are"], ["Which Filipino folk-rock band recorded Himig Natin?", "Juan de la Cruz Band", null, ["Juan de la Cruz"]],
]);

add("Music", [
  ["Who released the album Thriller?", "Michael Jackson", null, ["MJ"]],
  ["Who was the lead singer of Queen?", "Freddie Mercury", null, ["Freddie"]],
  ["Which English city did The Beatles form in?", "Liverpool"],
  ["How many numbered symphonies did Beethoven complete?", "Nine", null, ["9"]],
  ["How many keys are on a standard modern piano?", "88", null, ["eighty-eight", "88 keys"]],
  ["Which instrument family includes the violin, viola, and cello?", "Strings", null, ["string family", "string instruments"]],
  ["Which group launched Beyoncé to fame?", "Destiny's Child", null, ["Destinys Child"]],
  ["What number is the title of Adele's second studio album?", "21", null, ["twenty-one"]],
  ["Which Jamaican musician is strongly associated with reggae and the Wailers?", "Bob Marley", null, ["Marley"]],
  ["Who composed The Four Seasons?", "Antonio Vivaldi", null, ["Vivaldi"]],
  ["What other name is commonly used for the treble clef?", "G clef", null, ["G-clef"]],
  ["Which instrument did Louis Armstrong famously play?", "Trumpet", null, ["the trumpet"]],
  ["Which country did the group BTS form in?", "South Korea", null, ["Korea"]],
  ["What nickname is commonly used for Taylor Swift fans?", "Swifties", null, ["Swiftie"]],
  ["Who invented the saxophone?", "Adolphe Sax", null, ["Sax"]],
  ["Who composed the opera Carmen?", "Georges Bizet", null, ["Bizet"]],
  ["Which singer is known as the Material Girl?", "Madonna"],
  ["What is the lowest standard adult male singing voice?", "Bass", null, ["bass voice"]],
  ["Which band recorded Hotel California?", "Eagles", null, ["The Eagles"]],
  ["Which singer released Purple Rain?", "Prince"],
]);

add("TV Shows", [
  ["What coffee shop does the Friends group regularly visit?", "Central Perk", "Friends"],
  ["What is the name of Ross's pet monkey?", "Marcel", "Friends"],
  ["What song is Phoebe best known for performing?", "Smelly Cat", "Friends"],
  ["What is Chandler's surname?", "Bing", "Friends", ["Chandler Bing"]],
  ["What is Joey Tribbiani's profession?", "Actor", "Friends", ["an actor"]],
  ["What is Monica Geller's profession?", "Chef", "Friends", ["a chef"]],
  ["What is Rachel's surname?", "Green", "Friends", ["Rachel Green", "Greene"]],
  ["What is Ross Geller's academic profession?", "Paleontologist", "Friends", ["a paleontologist"]],
  ["Who is Monica's brother?", "Ross Geller", "Friends", ["Ross"]],
  ["Which Friend has an identical twin named Ursula?", "Phoebe Buffay", "Friends", ["Phoebe"]],

  ["What is Meredith's surname in Grey's Anatomy?", "Grey", "Grey's Anatomy", ["Meredith Grey"]],
  ["What is the hospital called at the beginning of Grey's Anatomy?", "Seattle Grace Hospital", "Grey's Anatomy", ["Seattle Grace"]],
  ["What nickname is given to Derek Shepherd?", "McDreamy", "Grey's Anatomy"],
  ["What surgical specialty does Cristina Yang pursue?", "Cardiothoracic surgery", "Grey's Anatomy", ["cardiothoracic", "cardio"]],
  ["Who created Grey's Anatomy?", "Shonda Rhimes", "Grey's Anatomy", ["Shonda"]],
  ["What is Dr. Bailey's first name?", "Miranda", "Grey's Anatomy", ["Miranda Bailey"]],
  ["Which surgical specialty does Alex Karev eventually choose?", "Pediatric surgery", "Grey's Anatomy", ["pediatrics", "pediatric surgeon"]],
  ["Who serves as chief of surgery when the series begins?", "Richard Webber", "Grey's Anatomy", ["Webber"]],
  ["What is Callie Torres's surgical specialty?", "Orthopedic surgery", "Grey's Anatomy", ["orthopedics", "orthopedic surgeon"]],
  ["What is the name of Meredith Grey's surgeon mother?", "Ellis Grey", "Grey's Anatomy", ["Ellis"]],

  ["In which fictional Texas town does Young Sheldon begin?", "Medford", "Young Sheldon", ["Medford, Texas"]],
  ["What is Sheldon's twin sister called?", "Missy", "Young Sheldon", ["Melissa Cooper", "Missy Cooper"]],
  ["What is Sheldon's older brother called?", "Georgie", "Young Sheldon", ["George Cooper Jr.", "George Jr"]],
  ["What is Sheldon's mother's name?", "Mary Cooper", "Young Sheldon", ["Mary"]],
  ["What is Sheldon's father's name?", "George Cooper Sr.", "Young Sheldon", ["George Sr", "George Cooper"]],
  ["What does Sheldon call his grandmother?", "Meemaw", "Young Sheldon", ["Connie", "Connie Tucker"]],
  ["Which pastor leads the Cooper family's church?", "Pastor Jeff", "Young Sheldon", ["Jeff Difford"]],
  ["Which university does Sheldon attend before moving to California?", "East Texas Tech", "Young Sheldon", ["East Texas Technical University"]],
  ["What subject is Sheldon exceptionally gifted at?", "Physics", "Young Sheldon"],
  ["Which actor plays young Sheldon?", "Iain Armitage", "Young Sheldon", ["Armitage"]],

  ["Who is Sheldon's roommate at the start of The Big Bang Theory?", "Leonard Hofstadter", "The Big Bang Theory", ["Leonard"]],
  ["What is the first name of Leonard and Sheldon's neighbor?", "Penny", "The Big Bang Theory"],
  ["What word does Sheldon use after many of his jokes?", "Bazinga", "The Big Bang Theory"],
  ["What is Sheldon's scientific field?", "Theoretical physics", "The Big Bang Theory", ["physics", "theoretical physicist"]],
  ["What kind of engineer is Howard Wolowitz?", "Aerospace engineer", "The Big Bang Theory", ["aerospace engineering"]],
  ["What is Raj Koothrappali's scientific field?", "Astrophysics", "The Big Bang Theory", ["astrophysicist"]],
  ["What is Amy Farrah Fowler's scientific field?", "Neurobiology", "The Big Bang Theory", ["neuroscience", "neurobiologist"]],
  ["Who owns the comic book store?", "Stuart Bloom", "The Big Bang Theory", ["Stuart"]],
  ["What frequently broken feature forces the characters to use the stairs?", "Elevator", "The Big Bang Theory", ["the elevator"]],
  ["At which university do Sheldon and Leonard work?", "Caltech", "The Big Bang Theory", ["California Institute of Technology"]],

  ["Who narrates most of How I Met Your Mother?", "Ted Mosby", "How I Met Your Mother", ["Ted"]],
  ["What is the Mother's name?", "Tracy McConnell", "How I Met Your Mother", ["Tracy"]],
  ["Which character is known for wearing suits?", "Barney Stinson", "How I Met Your Mother", ["Barney"]],
  ["What book contains Barney's dating strategies?", "The Playbook", "How I Met Your Mother", ["Playbook"]],
  ["What pub does the group regularly visit?", "MacLaren's Pub", "How I Met Your Mother", ["MacLarens", "MacLaren's"]],
  ["Which country is Robin Scherbatsky from?", "Canada", "How I Met Your Mother"],
  ["What is Marshall Eriksen's profession?", "Lawyer", "How I Met Your Mother", ["an attorney", "attorney"]],
  ["What is Lily Aldrin's profession at the start of the series?", "Kindergarten teacher", "How I Met Your Mother", ["teacher"]],
  ["What object becomes a symbol connected to the Mother?", "Yellow umbrella", "How I Met Your Mother", ["the yellow umbrella"]],
  ["What was Robin's Canadian pop-star name?", "Robin Sparkles", "How I Met Your Mother"],
]);

export const QUESTIONS = bank;
export const THEMES = [...new Set(bank.map((q) => q.theme).filter(Boolean))];
